rename namenumber_ namenumber
rename familymembers_count familymembers_coun
rename namefromearlier_ namefromearlier
rename sex_ sex
rename age_ age
rename comefrom_ comefrom
rename relationshiptohead_ relationshiptohead
rename maritalstatus_ maritalstatus
rename casteindividual_ casteindividual
rename religionindividual_ religionindividual
rename everattendedschool_ everattendedschool
rename classcompleted_ classcompleted
rename currentlyatschool_ currentlyatschool
rename educationexpenses_ educationexpenses
rename employment_count employment_coun
rename agefromearlier2_ agefromearlier2
rename namefromearlier3_ namefromearlier3
rename relationshiptoheadother_ relationshiptoheadother
rename casteindividualother_ casteindividualother
rename dummyworkedpastyear_ dummyworkedpastyear
rename occupationnumber_1_ occupationnumber_1
rename occupationname_1_ occupationname_1
rename kindofwork_1_ kindofwork_1
rename monthsayear_1_ monthsayear_1
rename daysamonth_1_ daysamonth_1
rename hoursaday_1_ hoursaday_1
rename annualincome_1_ annualincome_1
rename hoursayear_1_ hoursayear_1
rename joblocation_1_ joblocation_1
rename reasonnotworkpastyear_ reasonnotworkpastyear
rename occupationnumber_2_ occupationnumber_2
rename occupationname_2_ occupationname_2
rename kindofwork_2_ kindofwork_2
rename monthsayear_2_ monthsayear_2
rename daysamonth_2_ daysamonth_2
rename hoursaday_2_ hoursaday_2
rename annualincome_2_ annualincome_2
rename hoursayear_2_ hoursayear_2
rename joblocation_2_ joblocation_2
