*-------------------------
*Arnaud NATAL
*arnaud.natal@u-bordeaux.fr
*-----
*HOUSEHOLD LAST CLEAN FOR SURVEY MANUAL
*-----
*-------------------------

********** Clear
clear all
macro drop _all

********** Path to do
global dofile = "C:\Users\Arnaud\Documents\MEGA\Data\Publish\NEEMSIS-2"

********** Path to working directory directory
global directory = "C:\Users\Arnaud\Documents\MEGA\Data\Publish\NEEMSIS-2"
cd"$directory"




**********
use"NEEMSIS2-HH.dta", clear
**********




****************************************
* DROP EGOS VAR
****************************************
drop everwork workpastsevendays searchjob startbusiness reasondontsearchjob searchjobsince15 businessafter15 reasondontsearchjobsince15 nbermonthsearchjob kindofworkfirstjob unpaidinbusinessfirstjob agestartworking agestartworkingpaidjob methodfindfirstjob snfindfirstjob othermethodfindfirstjob jobfirstwagefrequencycash jobfirstwageamountcash monthstofindjob maxhoursayear selected_occupposition selected_occupname dummymainoccupation2 occupation1 occupation2 occupation3 occupation4 occupation5 occupation6 occupation7 occupation8 nbofoccupations othermainoccupation2 dummyseasonalmainoccup selected_months inddaysamonth_chithirai indhoursaday_chithirai indhoursamonth_chithirai inddaysamonth_vaikasi indhoursaday_vaikasi indhoursamonth_vaikasi inddaysamonth_aani indhoursaday_aani indhoursamonth_aani inddaysamonth_aadi indhoursaday_aadi indhoursamonth_aadi inddaysamonth_aavani indhoursaday_aavani indhoursamonth_aavani inddaysamonth_purataasi indhoursaday_purataasi indhoursamonth_purataasi inddaysamonth_iypasi indhoursaday_iypasi indhoursamonth_iypasi inddaysamonth_karthigai indhoursaday_karthigai indhoursamonth_karthigai inddaysamonth_maargazhi indhoursaday_maargazhi indhoursamonth_maargazhi inddaysamonth_thai indhoursaday_thai indhoursamonth_thai inddaysamonth_maasi indhoursaday_maasi indhoursamonth_maasi inddaysamonth_panguni indhoursaday_panguni indhoursamonth_panguni inddaysayear2 indhoursaday2 inddaysamonth3 indhoursaday3 indhoursamonth3 indhoursayear1 indhoursayear2 indhoursayear3 indhoursayear beforemainoccup otherbeforemainoccup otherbeforemainoccupduration mainoccuptype dummypreviouswagejob previousjobcontract reasonstoppedwagejob otherreasonstoppedjob annualincomeindself businessamountinvest businesslossinvest businesslossinvestamount covdifficulties businesssourceinvest otherbusinesssourceinvestment numberbusinessloan snbusinesslender1 snbusinesslender2 snbusinesslender3 snbusinesslender4 snbusinesslender5 snbusinesslender6 businessnbworkers dummybusinessunpaidworkers businessnbunpaidworkers businessnbfamilyworkers dummybusinesspaidworkers businessnbpaidworkers businessworkersfrequency businesslaborcost frequencygrossreceipt amountgrossreceipt businessfixedcosts businessfixedcostsamount businessexpenses businesssocialsecurity businesspaymentinkind businesspaymentinkindlist businesspaymentinkindvalue_food businesspaymentinkindvalue_trsp snrecruitworker snrecruitworkernamelist snrecruitworkername1 snrecruitworkername2 snrecruitworkername3 snrecruitworkername4 snrecruitworkername5 contract wagejobtype wagejobsocialsecurity jobwagefrequencycash jobwageamountcash wageamountmonth wageamountmonth1 wageamountmonth2 wageamountmonth3 wageamountmonth4 wagejobpaymentinkind wagejobpaymentinkindlist wagejobpaymentinkindvalue_clot wagejobpaymentinkindvalue_food wagejobpaymentinkindvalue_trsp wagejobpaymentinkindvalue_acco sumwagejobpaymentinkindvalue decisionwork decisionearnwork opinionworkingwoman opinionactivewoman decisionworkother decisionearnworkother readystartjob methodfindjob jobpreference moveoutsideforjob moveoutsideforjobreason moveoutsideforjobreasonother aspirationminimumwage dummyaspirationmorehours reasondontworkmore aspirationminimumwage2 respect workmate useknowledgeatwork satisfyingpurpose schedule takeholiday agreementatwork1 agreementatwork2 agreementatwork3 agreementatwork4 changework happywork satisfactionsalary executionwork1 executionwork2 executionwork3 executionwork4 executionwork5 executionwork6 executionwork7 executionwork8 executionwork9 accidentalinjury losswork lossworknumber mostseriousincident mostseriousinjury seriousinjuryother physicalharm problemwork1 problemwork2 problemwork4 problemwork5 problemwork6 problemwork7 problemwork8 problemwork9 problemwork10 workexposure1 workexposure2 workexposure3 workexposure4 workexposure5 professionalequipment break retirementwork verbalaggression physicalagression sexualharassment sexualaggression discrimination1 discrimination2 discrimination3 discrimination4 discrimination5 discrimination6 discrimination7 discrimination8 discrimination9 resdiscrimination1 resdiscrimination2 resdiscrimination3 resdiscrimination4 resdiscrimination5 rurallocation lackskill a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10 b11 b12 ab1 ab2 ab3 ab4 ab5 ab6 ab7 ab8 ab9 ab10 ab11 ab12 enjoypeople curious organized managestress interestedbyart tryhard workwithother makeplans sharefeelings nervous stickwithgoals repetitivetasks shywithpeople workhard changemood understandotherfeeling inventive enthusiastic feeldepressed appointmentontime trustingofother goaftergoal easilyupset talktomanypeople liketothink finishwhatbegin putoffduties rudetoother finishtasks toleratefaults worryalot easilydistracted keepworking completeduties talkative newideas staycalm forgiveother activeimagination expressingthoughts helpfulwithothers canreadcard1a canreadcard1b canreadcard1c canreadcard2 numeracy1 numeracy2 numeracy3 numeracy4 numeracy5 numeracy6 locuscontrol1 locuscontrol2 locuscontrol3 locuscontrol4 locuscontrol5 locuscontrol6 associationlist covassociationhelp covassociationhelplist covassociationhelplistother covassociationhelptype covassociationhelptypeother snrecommendassoname1 snrecommendassoname10 snrecommendassoname11 snrecommendassoname12 snrecommendassoname13 snrecommendassoname14 snrecommendassoname15 snrecommendassoname16 snrecommendassoname17 snrecommendassoname18 snrecommendassoname19 snrecommendassoname2 snrecommendassoname20 snrecommendassoname21 snrecommendassoname22 snrecommendassoname23 snrecommendassoname24 snrecommendassoname3 snrecommendassoname4 snrecommendassoname5 snrecommendassoname6 snrecommendassoname7 snrecommendassoname8 snrecommendassoname9 associationtype1 associationname1 assodegreeparticip1 assosize1 dummyassorecommendation1 snrecommendasso1 dummyassohelpjob1 assohelpjob1 assohelpjob_hiredyou1 assohelpjob_referredyou1 assohelpjob_sharedjob1 assohelpjob_helpwithappli1 assohelpjob_other1 assocotherhelpjob1 dummyassohelpbusiness1 assohelpbusiness1 associationtype2 associationname2 assodegreeparticip2 assosize2 dummyassorecommendation2 dummyassohelpjob2 assohelpjob2 assohelpjob_hiredyou2 assohelpjob_referredyou2 assohelpjob_sharedjob2 assohelpjob_helpwithappli2 assohelpjob_other2 assocotherhelpjob2 snfindcurrentjob snfindcurrentjobname1 snfindcurrentjobname2 snfindcurrentjobname3 snfindcurrentjobname4 snfindcurrentjobname5 snfindcurrentjobnamelist snfindjob snfindjobname1 snfindjobname2 snfindjobname3 snfindjobname4 snfindjobname5 snfindjobnamelist snrecommendforjob snrecommendforjobnamelist snrecommendforjobname1 snrecommendforjobname2 snrecommendforjobname3 snrecommendforjobname4 snrecommendforjobname5 snrecojobsuccess snrecojobsuccessname1 snrecojobsuccessname2 snrecojobsuccessname3 snrecojobsuccessname4 snrecojobsuccessname5 snrecojobsuccessnamelist sntalkthemost sntalkthemostname1 sntalkthemostname2 sntalkthemostname3 sntalkthemostname4 snhelpemergency snhelpemergencyname1 snhelpemergencyname2 snhelpemergencyname3 snhelpemergencyname4 snhelpemergencyname5 sncloserelouthh sncloserelouthhname1 sncloserelouthhname2 sncloserelouthhname3 sncloserelouthhname4 covsnhelpreceived covsnhelpreceivedlist covsnhelpreceivedname1 covsnhelpreceivedname2 covsnhelpreceivedname3 covsnhelpreceivedname4 covsnhelpreceivedname5 covsnhelpgiven covsnhelpgivenlist nbercontactphone nberpersonfamilyevent contactlist dummycontactleaders contactleaders nbcontact_headbusiness nbcontact_policeman nbcontact_civilserv nbcontact_bankemployee nbcontact_panchayatcommittee nbcontact_peoplecouncil nbcontact_recruiter nbcontact_headunion networktrustneighborhood covneworktrustneighborhood networktrustemployees networkpeoplehelping covnetworkpeoplehelping networkhelpkinmember covnetworkhelpkinmember covinstit1 covinstit2 covinstit3 covinstit4 covinstit5 covcontactinstitution covinstit6 covinstit7 covinstit8 covinstit9 covinstit10 covmostefficienthelp covmostefficienthelpother covmostefficienthelpopen businesspaymentinkindvalue_clot businesspaymentinkindvalue_acco businesspaymentinkindvalue_labo wagejobpaymentinkindvalue_labo assootherhelpbusiness1 snrecommendasso2 dummyassohelpbusiness2 assohelpbusiness2 assootherhelpbusiness2






****************************************
* DROP CONSTRUCT VAR
****************************************
drop goldquantityamount amountownlanddry amountownlandwet amountownland edulevel s_goldquantity goodtotalamount2 assets assets_noland ra1 rab1 rb1 ra2 rab2 rb2 ra3 rab3 rb3 ra4 rab4 rb4 ra5 rab5 rb5 ra6 rab6 rb6 ra7 rab7 rb7 ra8 rab8 rb8 ra9 rab9 rb9 ra10 rab10 rb10 ra11 rab11 rb11 ra12 rab12 rb12 set_a set_ab set_b raven_tt refuse num_tt lit_tt curious_backup interestedbyart_backup repetitivetasks_backup inventive_backup liketothink_backup newideas_backup activeimagination_backup organized_backup makeplans_backup workhard_backup appointmentontime_backup putoffduties_backup easilydistracted_backup completeduties_backup enjoypeople_backup sharefeelings_backup shywithpeople_backup enthusiastic_backup talktomanypeople_backup talkative_backup expressingthoughts_backup workwithother_backup understandotherfeeling_backup trustingofother_backup rudetoother_backup toleratefaults_backup forgiveother_backup helpfulwithothers_backup managestress_backup nervous_backup changemood_backup feeldepressed_backup easilyupset_backup worryalot_backup staycalm_backup tryhard_backup stickwithgoals_backup goaftergoal_backup finishwhatbegin_backup finishtasks_backup keepworking_backup ars ars2 ars3 cr_curious cr_interestedbyart cr_repetitivetasks cr_inventive cr_liketothink cr_newideas cr_activeimagination cr_organized cr_makeplans cr_workhard cr_appointmentontime cr_putoffduties cr_easilydistracted cr_completeduties cr_enjoypeople cr_sharefeelings cr_shywithpeople cr_enthusiastic cr_talktomanypeople cr_talkative cr_expressingthoughts cr_workwithother cr_understandotherfeeling cr_trustingofother cr_rudetoother cr_toleratefaults cr_forgiveother cr_helpfulwithothers cr_managestress cr_nervous cr_changemood cr_feeldepressed cr_easilyupset cr_worryalot cr_staycalm cr_tryhard cr_stickwithgoals cr_goaftergoal cr_finishwhatbegin cr_finishtasks cr_keepworking cr_OP cr_CO cr_EX cr_AG cr_ES cr_Grit OP CO EX AG ES Grit mainocc_kindofwork_indiv mainocc_profession_indiv mainocc_occupation_indiv mainocc_sector_indiv mainocc_hoursayear_indiv mainocc_annualincome_indiv mainocc_jobdistance_indiv mainocc_occupationname_indiv annualincome_indiv nboccupation_indiv occinc_indiv_agri occinc_indiv_agricasual occinc_indiv_nonagricasual occinc_indiv_nonagriregnonqual occinc_indiv_nonagriregqual occinc_indiv_selfemp occinc_indiv_nrega worker mainocc_kindofwork_HH mainocc_occupation_HH annualincome_HH nboccupation_HH occinc_HH_agri occinc_HH_agricasual occinc_HH_nonagricasual occinc_HH_nonagriregnonqual occinc_HH_nonagriregqual occinc_HH_selfemp occinc_HH_nrega working_pop remreceivedtotalamount_indiv remreceivedtotalamount_HH incomeassets_HH incomeassets_indiv otherhouserent_HH otherhouserent_indiv pension_indiv pension_HH totalincome_indiv totalincome_HH loans_indiv loanamount_indiv imp1_ds_tot_indiv imp1_is_tot_indiv loans_HH loanamount_HH imp1_ds_tot_HH imp1_is_tot_HH caste2010 caste2010_str caste2016 caste2016_str

drop year Suganya_and_Malarvizhi Raichal Rajalakschmi Chithra_and_Radhika Mayan Pazani Vivek_Radja










****************************************
* ADD LAST MODULES
****************************************
********** Setof
preserve
use"NEEMSIS2-setof", clear
keep HHID_panel INDID2020 setofmemberlistpreload2016 setoflefthome_o setofindividualid_o setoffamilymembers_o setofeducation_o setofemployment_o setofmigrationgroup_o setofremreceivedgroup_o setofremsentgroup_o setofloansbyborrower_o setofmainloans setoflendingmoney_o setofrecommendationgiven_o setofchitfund_o setofsavings_o setofgold_o setofinsurance_o setofmarriagegroup_o setofschemenregaind_o setofcashassistancemarriage_o setofgoldmarriagegroup_o setofschemepension1group_o setofschemepension2group_o setofschemepension3group_o setofschemepension4group_o setofschemepension5group_o setofschemepension6group_o setofschemepension7group_o setofindoccupmonths setofbusinessloandetails setofbusinesspaymentinkindgroup setofsnrecruitworkerid setofsnrecruitworkergroup setofwagejobpaymentinkindgroup setofcovoccupationfieldlist setofformalsocialcapital setofsnfindcurrentjobid setofsnfindcurrentjobgroup setofsnfindjobid setofsnfindjobgroup setofsnrecommendforjobid setofsnrecommendforjobgroup setofsnrecojobsuccessid setofsnrecojobsuccessgroup setofsntalkthemostid setofsntalkthemostgroup setofsnhelpemergencyid setofsnhelpemergencygroup setofsncloserelouthhid setofsncloserelouthhgroup setofcovsnhelpreceivedid setofcovsnhelpreceivedgroup setofcovsntypehelpreceivedgroup setofcovsnhelpgivenid setofcovsnhelpgivengroup setofcovsntypehelpgivengroup setofcontactgroup setoffamilymembers setofeducation setofemployment setofindividualid setoflefthome setofremreceivedidgroup setofremsentidgroup setofmigrationidgroup setofloansbyborrower setoflendingmoney setofrecommendationgiven setofchitfund setofsavings setofgold setofinsurance setofmarriagegroup setofschemenregaind setofcashassistancemarriagegroup setofgoldmarriagegroup setofschemepension1group setofschemepension2group setofschemepension3group setofschemepension4group setofschemepension5group setofschemepension6group setofschemepension7group setofoccupations setofmigrationjobidgroup setofremreceivedsourceidgroup setofremsentidgroup_old setofdetailsloanbyborrower setofdetailschitfunds setofdetailssavingaccounts setofdetailsinsurance setofremreceivedgroup setofremsentgroup setofmarriagefinance setofmarriagegift
order HHID_panel INDID2020
sort HHID_panel INDID2020
duplicates report HHID_panel INDID2020
save"temp_NEEMSIS2-setof.dta", replace
restore

duplicates report HHID_panel INDID2020
merge 1:1 HHID_panel INDID2020 using "temp_NEEMSIS2-setof.dta", force
drop if _merge==2
drop _merge


********** Gold
preserve
use"NEEMSIS2-gold.dta", replace
drop dummygold  goldquantity dummygoldpledged goldquantitypledge goldamountpledge covgoldpledged goldreasonpledge loanamountgold lenderscastegold lenderfromgold loansettledgold loanbalancegold loandategold goldreasonpledgemain loanlendergold
restore


********** Goldloan
preserve
use"NEEMSIS2-goldloans.dta", replace
restore


********** Marriage
preserve
use"NEEMSIS2-marriage.dta", replace
drop dummymarriage marriagesomeoneelse marriagetype marriageblood marriagearranged marriagedecision marriagespousefamily marriagedowry marriagetotalcost marriagehusbandcost marriagewifecost howpaymarriage marriageloannb marriageexpenses dummymarriagegift marriagegiftsource marriagedate
restore


********** Marriage finance
preserve
use"NEEMSIS2-marriagefinance.dta", replace
*with loans
restore



********** Marriage gift
preserve
use"NEEMSIS2-marriagegift.dta", clear
drop marriagegifttype_2 marriagegifttype_1 marriagegifttype_4 marriagegifttype_3 marriagegifttype_5 marriagegifttype_77
destring marriagegiftsourceid, replace
reshape wide marriagegiftsourcename marriagegiftsourcenb marriagegifttype marriagegiftamount marriagegoldquantityasgift, i(setofmarriagegroup) j(marriagegiftsourceid)
rename setofmarriagegroup setofmarriagegift
save"NEEMSIS2-marriagegift_wide.dta", replace
restore

split setofmarriagegift, p(/)
egen setofmarriagegiftnew=concat(setofmarriagegift1 setofmarriagegift2), p(/)
drop setofmarriagegift setofmarriagegift1 setofmarriagegift2 setofmarriagegift3
rename setofmarriagegiftnew setofmarriagegift

merge m:1 setofmarriagegift using "NEEMSIS2-marriagegift_wide.dta"
drop if _merge==2
drop _merge



********** Remittances sent
preserve
use"NEEMSIS2-remsent.dta", clear
drop remsentservices_2 remsentservices_4 remsentservices_3 remsentservices_1 remsentmean_1 remsentmean_3 remsentmean_2 remsentservices_5 remsentservices_77 remsentmean_77
gen test=1 if remsentname2!=remsentname3
ta test
sort test
drop test remsentname2
rename remsentname3 remsentnametwo
rename remsentname1 remsentname
destring remsentid, replace
reshape wide remsentname remsentnametwo remsentdummyvillage remsentrelation remsentoccup remsentplace remsentmoney remsentgift remsentservices remsentsourceoccupother remsentservicesother remsentfrequency remsentamount remsenttotalamount remsentmean remsentgiftnb remsentgiftamount covremsent, i(setofremsentidgroup) j(remsentid)
rename setofremsentidgroup setofremsentgroup
tab1 setof*
duplicates report setofremsentgroup
save"NEEMSIS2-remsent_wide.dta", replace
*271
restore

split setofremsentidgroup_old, p(/)
egen setofremsentgroup2=concat(setofremsentidgroup_old1 setofremsentidgroup_old2), p(/)
replace setofremsentgroup2="" if setofremsentgroup2=="/"
replace setofremsentgroup=setofremsentgroup2 if setofremsentgroup=="" & setofremsentgroup2!=""
fre setofremsentgroup
duplicates report setofremsentgroup
merge m:1 setofremsentgroup using "NEEMSIS2-remsent_wide"
drop _merge



********** Remittances received
preserve
use"NEEMSIS2-remreceived.dta", clear
drop remreceivedservices_2 remreceivedservices_4 remreceivedservices_3 remreceivedservices_5 remreceivedmean_1 remreceivedmean_3 remreceivedmean_2 remreceivedservices_1 remreceivedservices_77 remreceivedmean_77
gen test=1 if remrecipientsourcename2!=remrecipientsourcename3
ta test
drop test
drop remrecipientsourcename2
rename remrecipientsourcename3 remrecipientsourcenametwo
rename remrecipientsourcename1 remrecipientsourcename
destring remrecipientsourceid, replace
reshape wide remrecipientsourcename remrecipientsourcenametwo remreceivedsourcerelation remreceivedsourceoccup remreceivedsourceplace remreceivedmoney remgift remreceivedservices remreceivedfrequency remreceivedamount remreceivedtotalamount remreceivedmean remgiftnb remgiftamount remreceivedsourceoccupother remreceivedservicesother covremreceived, i(setofremreceivedidgroup) j(remrecipientsourceid)
save"NEEMSIS2-remreceived_wide.dta", replace
duplicates report setofremreceivedidgroup
*473
restore

fre setofremreceivedsourceidgroup
split setofremreceivedsourceidgroup, p(/)
egen setofremreceivedidgroup2=concat(setofremreceivedsourceidgroup1 setofremreceivedsourceidgroup2), p(/)
replace setofremreceivedidgroup2="" if setofremreceivedidgroup2=="/"
rename setofremreceivedidgroup setofremreceivedidgroup22
rename setofremreceivedidgroup2 setofremreceivedidgroup

merge m:1 setofremreceivedidgroup using "NEEMSIS2-remreceived_wide.dta"
drop _merge



drop setofemployment setofmarriagegroup setofremreceivedsourceidgroup setofremsentidgroup_old setofdetailsloanbyborrower setofremreceivedgroup setofremsentgroup setofmemberlistpreload2016 setoflefthome_o setofindividualid_o setoffamilymembers_o setofeducation_o setofemployment_o setofremreceivedgroup_o setofremsentgroup_o setofloansbyborrower_o setofmainloans setoflendingmoney_o setofrecommendationgiven_o setofchitfund_o setofsavings_o setofgold_o setofinsurance_o setofmarriagegroup_o setofschemenregaind_o setofcashassistancemarriage_o setofgoldmarriagegroup_o setofschemepension1group_o setofschemepension2group_o setofschemepension3group_o setofschemepension4group_o setofschemepension5group_o setofschemepension6group_o setofschemepension7group_o setofindoccupmonths setofbusinessloandetails setofbusinesspaymentinkindgroup setofsnrecruitworkerid setofsnrecruitworkergroup setofwagejobpaymentinkindgroup setofcovoccupationfieldlist setofformalsocialcapital setofsnfindcurrentjobid setofsnfindcurrentjobgroup setofsnfindjobid setofsnfindjobgroup setofsnrecommendforjobid setofsnrecommendforjobgroup setofsnrecojobsuccessid setofsnrecojobsuccessgroup setofsntalkthemostid setofsntalkthemostgroup setofsnhelpemergencyid setofsnhelpemergencygroup setofsncloserelouthhid setofsncloserelouthhgroup setofcovsnhelpreceivedid setofcovsnhelpreceivedgroup setofcovsntypehelpreceivedgroup setofcovsnhelpgivenid setofcovsnhelpgivengroup setofcovsntypehelpgivengroup setofcontactgroup setoffamilymembers setofeducation setofindividualid setoflefthome setofremreceivedidgroup22 setofremsentidgroup setofloansbyborrower setoflendingmoney setofrecommendationgiven setofchitfund setofsavings setofgold setofinsurance setofschemenregaind setofcashassistancemarriagegroup setofgoldmarriagegroup setofschemepension1group setofschemepension2group setofschemepension3group setofschemepension4group setofschemepension5group setofschemepension6group setofschemepension7group setofoccupations setofdetailschitfunds setofdetailssavingaccounts setofdetailsinsurance setofmarriagefinance setofmarriagegift setofremsentidgroup_old1 setofremsentidgroup_old2 setofremsentidgroup_old3 setofremsentgroup2 setofremreceivedsourceidgroup1 setofremreceivedsourceidgroup2 setofremreceivedsourceidgroup3 setofremreceivedidgroup







****************************************
* ORDER FOR QUESTIONNAIRE
****************************************
order numformerfamily numleftfamily instancename formdef_version parent_key_BaseAgri address_BaseAgri submissiondate_BaseAgri geopointlatitude_BaseAgri geopointlongitude_BaseAgri geopointaltitude_BaseAgri geopointaccuracy_BaseAgri villagename_BaseAgri villagearea_BaseAgri namenewhead sondaughter sondaughtername issue_new childname_modif ///
 HHID_panel INDID_panel householdidparent_backup householdidparent_key parent_key INDID2020 INDID_total INDID_former INDID_new INDID_left INDID egoid start_HH_quest start_agri_quest end_HH_quest end_agri_quest submissiondate geopointlatitude geopointlongitude geopointaltitude geopointaccuracy username_str compensation compensationamount villagename villageid villagearea villageareaid householdid2020 value_householdid_2020 householdid_int newfrompanel villagenameparent villageareaparent householdidparent, first
 

********** General information
order interviewplace address lefthousehold reasonlefthome reasonlefthomeother lefthomedurationmoreoneyear lefthomedestination othermember name interviewer jatis caste religion comefrom otherorigin numfamily livinghome lefthomedurationlessoneyear lefthomedestination lefthomereason dummylefthousehold lefthomeid lefthomename sex, after(householdidparent)


********** Family members details
order age jatis caste relationshiptohead relationshiptoheadother maritalstatus maritalstatusdate dummycastespouse comefromspouse dummyreligionspouse religionspouse castespouse otheroriginspouse, after(sex)
*othermember, formermember, etc. missings


********** Education
order canread everattendedschool classcompleted after10thstandard durationafter10th typeofhigheredu subjectsafter10th othersubjectsafter10th newtraining reservation reservationgrade reservationkind reservationother currentlyatschool educationexpenses amountschoolfees bookscost transportcost reasonneverattendedschool reasondropping otherreasondroppingschool covgoingbackschool decisiondropping decisiondroppingother dummyscholarship scholarshipamount scholarshipduration converseinenglish, after(otheroriginspouse)



********** Employment
order dummyworkedpastyear reservationemployment reasonnotworkpastyear stoppedworking workpastsixmonth everworksalaried kindofworkinactive, after(converseinenglish)


********** Migration
order dummymigration migrantlist dummy_migrantlist migrantid migrantname migrationjoblist, after(kindofworkinactive)



********** Remittances receveid
order dummyremreceived remrecipientlist dummy_remrecipientlist remrecipientid remrecipientname ///
remrecipientsourcename1 remrecipientsourcenametwo1 remreceivedsourcerelation1 remreceivedsourceoccup1 remreceivedsourceplace1 remreceivedmoney1 remgift1 remreceivedservices1 remreceivedfrequency1 remreceivedamount1 remreceivedtotalamount1 remreceivedmean1 remgiftnb1 remgiftamount1 remreceivedsourceoccupother1 remreceivedservicesother1 covremreceived1 ///
remrecipientsourcename2 remrecipientsourcenametwo2 remreceivedsourcerelation2 remreceivedsourceoccup2 remreceivedsourceplace2 remreceivedmoney2 remgift2 remreceivedservices2 remreceivedfrequency2 remreceivedamount2 remreceivedtotalamount2 remreceivedmean2 remgiftnb2 remgiftamount2 remreceivedsourceoccupother2 remreceivedservicesother2 covremreceived2 ///
remrecipientsourcename3 remrecipientsourcenametwo3 remreceivedsourcerelation3 remreceivedsourceoccup3 remreceivedsourceplace3 remreceivedmoney3 remgift3 remreceivedservices3 remreceivedfrequency3 remreceivedamount3 remreceivedtotalamount3 remreceivedmean3 remgiftnb3 remgiftamount3 remreceivedsourceoccupother3 remreceivedservicesother3 covremreceived3 ///
remrecipientsourcename4 remrecipientsourcenametwo4 remreceivedsourcerelation4 remreceivedsourceoccup4 remreceivedsourceplace4 remreceivedmoney4 remgift4 remreceivedservices4 remreceivedfrequency4 remreceivedamount4 remreceivedtotalamount4 remreceivedmean4 remgiftnb4 remgiftamount4 remreceivedsourceoccupother4 remreceivedservicesother4 covremreceived4 ///
, after(migrationjoblist)



********** Remittances sent
order dummyremsent remsenderlist dummy_remsenderlist remsenderid remsendername ///
remsentname1 remsentnametwo1 remsentdummyvillage1 remsentrelation1 remsentoccup1 remsentplace1 remsentmoney1 remsentgift1 remsentservices1 remsentsourceoccupother1 remsentservicesother1 remsentfrequency1 remsentamount1 remsenttotalamount1 remsentmean1 remsentgiftnb1 remsentgiftamount1 covremsent1 ///
remsentname2 remsentnametwo2 remsentdummyvillage2 remsentrelation2 remsentoccup2 remsentplace2 remsentmoney2 remsentgift2 remsentservices2 remsentsourceoccupother2 remsentservicesother2 remsentfrequency2 remsentamount2 remsenttotalamount2 remsentmean2 remsentgiftnb2 remsentgiftamount2 covremsent2 ///
remsentname3 remsentnametwo3 remsentdummyvillage3 remsentrelation3 remsentoccup3 remsentplace3 remsentmoney3 remsentgift3 remsentservices3 remsentsourceoccupother3 remsentservicesother3 remsentfrequency3 remsentamount3 remsenttotalamount3 remsentmean3 remsentgiftnb3 remsentgiftamount3 covremsent3 ///
remsentname4 remsentnametwo4 remsentdummyvillage4 remsentrelation4 remsentoccup4 remsentplace4 remsentmoney4 remsentgift4 remsentservices4 remsentsourceoccupother4 remsentservicesother4 remsentfrequency4 remsentamount4 remsenttotalamount4 remsentmean4 remsentgiftnb4 remsentgiftamount4 covremsent4 ///
remsentname5 remsentnametwo5 remsentdummyvillage5 remsentrelation5 remsentoccup5 remsentplace5 remsentmoney5 remsentgift5 remsentservices5 remsentsourceoccupother5 remsentservicesother5 remsentfrequency5 remsentamount5 remsenttotalamount5 remsentmean5 remsentgiftnb5 remsentgiftamount5 covremsent5 ///
, after(covremreceived4)






********** Financial practices
order dummyloans covrefusalloan borrowerlist dummy_borrowerlist sumhhloans threemainloans borrowerid borrowername nbloansbyborrower ///
loandetails1 loandetails2 loandetails3 loandetails4 loandetails5 loandetails6 loandetails7 loandetails8 loandetails9 loandetails10 loandetails11 loandetails12 loandetails13 loandetails14 loandetails15 loandetails16 loandetails17 loandetails18 loandetails19 loandetails20 loandetails21 loandetails22 loandetails23 loandetails24 loandetails25 loandetails26 loandetails27 loandetails28 loandetails29 loandetails30 loandetails31 loandetails32 loandetails33 loandetails34 loandetails35 loandetails36 loandetails37 loandetails41 loandetails42 loandetails43 loandetails44 loandetails49 loandetails50 loandetails51 loandetails52 loandetails53 loandetails54 loandetails55 loandetails56 loandetails65 loandetails66 loandetails67 loandetails68 loandetails69 loandetails70 loandetails71 loandetails72 loandetails73 loandetails74 loandetails75 loandetails76 loandetails77 loandetails78 loandetails79 ///
dummyincomeassets incomeassets ///
dummylendingmoney hhlenderlist dummy_hhlenderlist hhlenderid hhlendername borrowerscaste borrowerssex relationwithborrower amoutlent interestlending purposeloanborrower problemrepayment dummyloanfromborrower covlendrepayment covlending datelendingmoney ///
dummyrecommendgiven recommendgivenlist dummy_recommendgivenlist dummyrecommendrefuse reasonrefuserecommend recommendgivenid recommendgivenname ///
dummychitfund chitfundbelongerid dummy_chitfundbelongerid chitfundbelongernumber chitfundbelongername nbchitfunds chitfundtype1 durationchit1 nbermemberchit1 chitfundpayment1 chitfundpaymentamount1 chitfundamount1 covchitfundstop1 covchitfundreturn1 chitfundtype2 durationchit2 nbermemberchit2 chitfundpayment2 chitfundpaymentamount2 chitfundamount2 covchitfundstop2 covchitfundreturn2 chitfundtype3 durationchit3 nbermemberchit3 chitfundpayment3 chitfundpaymentamount3 chitfundamount3 covchitfundstop3 ///
dummysavingaccount savingsownerid dummy_savingsownerid savingsownernumber savingsownername nbsavingaccounts savingsaccounttype1 savingsjointaccount1 banktype1 savingsbankname1 savingsbankplace1 savingsamount1 savingspurpose1 covsavinguse1 dummydebitcard1 dummycreditcard1 covsavinguseamount1 usedebitcard1 reasonnotusedebitcard1 usecreditcard1 savingsaccountdate1 datedebitcard1 datecreditcard1 savingsaccounttype2 savingsjointaccount2 banktype2 savingsbankname2 savingsbankplace2 savingsamount2 savingspurpose2 covsavinguse2 dummydebitcard2 dummycreditcard2 covsavinguseamount2 usedebitcard2 savingsaccountdate2 datedebitcard2 savingsaccounttype3 banktype3 savingsbankname3 savingsbankplace3 savingsamount3 savingspurpose3 covsavinguse3 dummydebitcard3 dummycreditcard3 covsavinguseamount3 usedebitcard3 savingsaccountdate3 datedebitcard3 savingsaccounttype4 banktype4 savingsbankname4 savingsbankplace4 savingsamount4 savingspurpose4 covsavinguse4 dummydebitcard4 dummycreditcard4 usedebitcard4 savingsaccountdate4 datedebitcard4 ///
dummygold covsoldgold covsoldgoldquantity covlostgold goldownerid dummy_goldownerid goldnumber goldownername goldquantity dummygoldpledged goldquantitypledge goldamountpledge covgoldpledged goldreasonpledge goldreasonpledgemain loanamountgold loandategold loanlendergold lenderscastegold lenderfromgold loansettledgold loanbalancegold ///
dummyinsurance reasonnoinsurance insuranceownerid dummy_insuranceownerid insuranceownernumber insuranceownername nbinsurance ///
insurancepublic1 insurancename1 insurancejoineddate1 insurancetype1 insurancepaymentfrequency1 insuranceamount1 insurancebenefit1 insurancebenefitamount1 ///
insurancepublic2 insurancename2 insurancejoineddate2 insurancetype2 insurancepaymentfrequency2 insuranceamount2 insurancebenefit2 insurancebenefitamount2 ///
insurancepublic3 insurancename3 insurancejoineddate3 insurancetype3 insurancepaymentfrequency3 insuranceamount3 insurancebenefit3 insurancebenefitamount3 ///
insurancepublic4 insurancename4 insurancejoineddate4 insurancetype4 insurancepaymentfrequency4 insuranceamount4 insurancebenefit4 ///
insurancepublic5 insurancename5 insurancejoineddate5 insurancetype5 insurancepaymentfrequency5 insuranceamount5 insurancebenefit5 ///
insurancepublic6 insurancename6 insurancejoineddate6 insurancetype6 insurancepaymentfrequency6 insuranceamount6 insurancebenefit6 ///
usemobilefinance usemobilefinancetype usemobilefinanceother ///
, after(covremsent5)




********** Agriculture
drop landpurchasedhowbuy_6 landleasingrelation_5 productunitchoice* productcastelabourers_15 productcastelabourers_11

order dummyeverland2010 covsellland dummyeverhadland reasonnoland reasonnolandother ///
ownland sizeownland drywetownland sizedryownland sizewetownland waterfromownland leaseland sizeleaseland drywetleaseland waterfromleaseland landpurchased landpurchasedacres landpurchasedamount landpurchasedhowbuy landlost landlostreason dummyleasedland landleasername landleaserrelation landleasercaste dummyleasingland landleasingname landleasingrelation landleasingcaste ///
productlist ///
productname1 productacre1 productypeland1 productunit1 productnbchoice1 productselfconsumption1 productnbchoicesold1 productpricesold1 productexpenses1 productpaidworkers1 productnbpaidworkers1 productlabourcost1 productunpaidworkers1 productnbunpaidworkers1 productnbhhmembers1 productoriginlabourers1 productcastelabourers1 ///
productname2 productacre2 productypeland2 productunit2 productnbchoice2 productselfconsumption2 productnbchoicesold2 productpricesold2 productexpenses2 productpaidworkers2 productnbpaidworkers2 productlabourcost2 productunpaidworkers2 productnbunpaidworkers2 productnbhhmembers2 productoriginlabourers2 productcastelabourers2 ///
productname3 productacre3 productypeland3 productunit3 productnbchoice3 productselfconsumption3 productnbchoicesold3 productpricesold3 productexpenses3 productpaidworkers3 productnbpaidworkers3 productlabourcost3 productunpaidworkers3 productnbunpaidworkers3 productnbhhmembers3 productoriginlabourers3 productcastelabourers3 ///
productname4 productacre4 productypeland4 productunit4 productnbchoice4 productselfconsumption4 productnbchoicesold4 productpricesold4 productexpenses4 productpaidworkers4 productnbpaidworkers4 productlabourcost4 productunpaidworkers4 productnbunpaidworkers4 productnbhhmembers4 productoriginlabourers4 productcastelabourers4 ///
productname5 productacre5 productypeland5 productunit5 productnbchoice5 productselfconsumption5 productnbchoicesold5 productpricesold5 productexpenses5 productpaidworkers5 productnbpaidworkers5 productlabourcost5 productunpaidworkers5 productnbunpaidworkers5 productnbhhmembers5 productoriginlabourers5 productcastelabourers5 ///
productname9 productacre9 productypeland9 productunit9 productnbchoice9 productselfconsumption9 productnbchoicesold9 productpricesold9 productexpenses9 productpaidworkers9 productnbpaidworkers9 productlabourcost9 productunpaidworkers9 productnbunpaidworkers9 productnbhhmembers9 productoriginlabourers9 productcastelabourers9 ///
productname11 productacre11 productypeland11 productunit11 productnbchoice11 productselfconsumption11 productnbchoicesold11 productpricesold11 productexpenses11 productpaidworkers11 productnbpaidworkers11 productlabourcost11 productunpaidworkers11 productnbunpaidworkers11 productnbhhmembers11 productoriginlabourers11 ///
productcastelabourers11 productname12 productacre12 productypeland12 productunit12 productnbchoice12 productselfconsumption12 productnbchoicesold12 productpricesold12 productexpenses12 productpaidworkers12 productnbpaidworkers12 productlabourcost12 productunpaidworkers12 productnbunpaidworkers12 productnbhhmembers12 productoriginlabourers12 productcastelabourers12 ///
productname14 productother productacre14 productypeland14 productunit14 productnbchoice14 productselfconsumption14 productnbchoicesold14 productpricesold14 productexpenses14 productpaidworkers14 productnbpaidworkers14 productlabourcost14 productunpaidworkers14 productnbunpaidworkers14 productnbhhmembers14 productoriginlabourers14 productcastelabourers14 ///
, after(usemobilefinanceother)



*Suffix
fre productname1 productname2 productname3 productname4 productname5 productname9 productname11 productname12 productname14

foreach x in productname productacre productypeland productunit productnbchoice productselfconsumption productnbchoicesold productpricesold productexpenses productpaidworkers productnbpaidworkers productlabourcost productunpaidworkers productnbunpaidworkers productnbhhmembers productoriginlabourers productcastelabourers {
rename `x'1  `x'_paddy
rename `x'2  `x'_cotton
rename `x'3  `x'_sugarcane
rename `x'4  `x'_savukku
rename `x'5  `x'_guava
rename `x'9  `x'_groundnut
rename `x'11 `x'_millets
rename `x'12 `x'_cashew
rename `x'14 `x'_other
}

drop productname*




********** COV + Livestock
order covsubsistence covsubsistencereason covsubsistencesize covsubsistencenext covsubsistencereasonother covharvest covselfconsumption covharvestquantity covharvestprices ///
livestocklist ///
livestocknb_cow livestockprice_cow livestockamount_cow livestockuse_cow ///
livestocknb_goat livestockprice_goat livestockamount_goat livestockuse_goat  /// 
livestocknb_chicken livestockprice_chicken livestockamount_chicken livestockuse_chicken ///
livestocknb_bullock livestockprice_bullock livestockamount_bullock livestockuse_bullock ///
livestocknb_bullforploughing livestockprice_bullforploughing livestockamount_bullforploughing livestockuse_bullforploughing ///
covselllivestock covselllivestock_cow covselllivestock_goat covselllivestock_chicken covselllivestock_bullock covselllivestock_bullforploughin covselllivestock_none ///
dummycattleloss dummycattlesold cattlesoldreason equipmentlist ///
, after(productcastelabourers_other)




********** Equipment
rename equipementyear1 equipmentyear_tractor
rename equipementyear2 equipmentyear_bullockcart
rename equipementyear4 equipmentyear_plowingmach
drop equipmentlist_*

order equipmentname_tractor equipmentnb_tractor equipmentyear_tractor equipmentcost_tractor equipmentpledged_tractor ///
equipmentname_bullockcart equipmentnb_bullockcart equipmentyear_bullockcart equipmentcost_bullockcart equipmentpledged_bullockcart ///
equipmentname_plowingmach equipmentnb_plowingmach equipmentyear_plowingmach equipmentcost_plowingmach equipmentpledged_plowingmach ///
equipmentborrowedlist equipmentborrowedlist_tractor equipmentborrowedlist_bullockcar equipmentborrowedlist_harvester equipmentborrowedlist_plowingmac equipmentborrowedlist_none ///
covsellequipment covsellequipment_tractor covsellequipment_bullockcar covsellequipment_harvester covsellequipment_plowingmac covsellequipment_none ///
, after(equipmentlist)

drop equipmentname*


********** Decision + cov
order decisionconsumption foodexpenses decisionhealth healthexpenses ceremoniesexpenses ceremoniesrelativesexpenses deathexpenses covfoodenough covfoodquality covgenexpenses covexpensesdecrease covexpensesincrease covexpensesstable covplacepurchase covsick, after(covsellequipment_none)





********** Consumption
order listgoods othergood goodname_car numbergoods_car goodyearpurchased_car goodtotalamount_car goodbuying_car goodname_bike numbergoods_bike goodyearpurchased_bike goodtotalamount_bike goodbuying_bike goodsourcecredit_bike goodcreditsettled_bike goodname_fridge numbergoods_fridge goodyearpurchased_fridge goodtotalamount_fridge goodbuying_fridge goodsourcecredit_fridge goodcreditsettled_fridge goodname_furniture numbergoods_furniture goodyearpurchased_furniture goodtotalamount_furniture goodbuying_furniture goodname_tailormach numbergoods_tailormach goodyearpurchased_tailormach goodtotalamount_tailormach goodbuying_tailormach goodname_phone numbergoods_phone goodyearpurchased_phone goodtotalamount_phone goodbuying_phone goodsourcecredit_phone goodcreditsettled_phone goodname_landline numbergoods_landline goodyearpurchased_landline goodtotalamount_landline goodbuying_landline goodname_camera numbergoods_camera goodyearpurchased_camera goodtotalamount_camera goodbuying_camera goodname_cookgas numbergoods_cookgas goodyearpurchased_cookgas goodtotalamount_cookgas goodbuying_cookgas goodsourcecredit_cookgas goodcreditsettled_cookgas goodname_computer numbergoods_computer goodyearpurchased_computer goodtotalamount_computer goodbuying_computer goodname_antenna numbergoods_antenna goodyearpurchased_antenna goodtotalamount_antenna goodbuying_antenna covsellgoods covsellgoods_car covsellgoods_bike covsellgoods_fridge covsellgoods_furniture covsellgoods_tailormach covsellgoods_phone covsellgoods_landline covsellgoods_DVD covsellgoods_camera covsellgoods_cookgas covsellgoods_computer covsellgoods_antenna covsellgoods_other covsellgoods_none covsellgoodsother, after(covsick)


drop goodname* goodtotalamount_DVD


********** Marriage
order dummymarriage marriedlist dummy_marriedlist marriedname marriedid marriagesomeoneelse marriagedate peoplewedding husbandwifecaste marriagetype marriageblood marriagearranged marriagedecision marriagespousefamily marriagedowry engagementtotalcost engagementhusbandcost engagementwifecost marriagetotalcost marriagehusbandcost marriagewifecost howpaymarriage marriageloannb ///
marriageexpenses dummymarriagegift marriagegiftsource ///
marriagegiftsourcename1 marriagegiftsourcenb1 marriagegifttype1 marriagegiftamount1 marriagegoldquantityasgift1 marriagegiftsourcename2 marriagegiftsourcenb2 marriagegifttype2 marriagegiftamount2 marriagegoldquantityasgift2 marriagegiftsourcename3 marriagegiftsourcenb3 marriagegifttype3 marriagegiftamount3 marriagegoldquantityasgift3 marriagegiftsourcename4 marriagegiftsourcenb4 marriagegifttype4 marriagegiftamount4 marriagegoldquantityasgift4 marriagegiftsourcename5 marriagegiftsourcenb5 marriagegifttype5 marriagegiftamount5 marriagegoldquantityasgift5 marriagegiftsourcename9 marriagegiftsourcenb9 marriagegifttype9 marriagegiftamount9 marriagegoldquantityasgift9 marriagegiftsourcename10 marriagegiftsourcenb10 marriagegifttype10 marriagegiftamount10 marriagegoldquantityasgift10 ///
marriagepb ///
, after(covsellgoodsother)

drop marriagepb







********** Housing
order house howbuyhouse covsellhouse rentalhouse housevalue housetype housesize houseroom housetitle ownotherhouse covsellplot otherhouserent otherhousevalue dummysaleproperty incomesaleproperty useincomesaleproperty electricity water toiletfacility notoiletreason noowntoilet, after(marriagegoldquantityasgift10)


*rename dummy_schemerecipientlist7 dummy_cashmarriagerecipientlist



********** Schemes HH
drop dummy_schemeslist

***** Ration card
order schemeslist ///
rationcardnber rationcardmembers rationcarduse covrationcarduse covproductavailability rationcardreasonnouse, after(noowntoilet)


***** Free house
rename freehousescheme scheme_freehouse
rename housingschemesdate schemedate_freehouse
rename freehousebenefittype schemetype_freehouse
rename schemeamount0 schemeamount_freehouse

order  scheme_freehouse schemedate_freehouse schemetype_freehouse schemeamount_freehouse, after(rationcardreasonnouse)


***** Cash assitance funeral
rename schemeyearbenefited1 schemedate_cashfuneral
rename schemeamount1 schemeamount_cashfuneral
order schemedate_cashfuneral schemeamount_cashfuneral, after(schemeamount_freehouse)


***** Free patta
rename schemeyearfreepatta schemedate_freepatta
rename schemeamountfreepatta schemeamount_freepatta
order schemedate_freepatta schemeamount_freepatta, after(schemeamount_cashfuneral)


***** Girl Children protection scheme
rename schemeyeargirlprotection schemedate_girlprotection
rename schemeamountgirlprotection schemeamount_girlprotection
order schemedate_girlprotection schemeamount_girlprotection, after(schemeamount_freepatta)


***** SHG loan subsidy
rename schemeyearshgloan schemedate_shgloan
rename schemeamountshgloan schemeamount_shgloan
order schemedate_shgloan schemeamount_shgloan, after(schemeamount_girlprotection)


***** Free cows and goats scheme
rename schemeyearbenefited2 schemedate_freecows
rename schemeamount2 schemeamount_freecows
order schemedate_freecows schemeamount_freecows, after(schemeamount_shgloan)


***** Free LPG gas cylinder scheme
rename schemeyearbenefited3 schemedate_freelpg
rename schemeamount3 schemeamount_freelpg
order schemedate_freelpg schemeamount_freelpg, after(schemeamount_freecows)


***** Education fees subsidy scheme
rename schemeyearbenefited4 schemedate_educfees
rename schemeamount4 schemeamount_educfees
order schemedate_educfees schemeamount_educfees, after(schemeamount_freelpg)


***** Subsidy for farm equipment scheme
rename schemeyearbenefited5 schemedate_farmequip
rename schemeamount5 schemeamount_farmequip
order schemedate_farmequip schemeamount_farmequip, after(schemeamount_educfees)


***** Government land scheme
rename schemelandyearbenefited schemedate_land
rename schemelandsize schemesize_land
order schemedate_land schemesize_land, after(schemeamount_farmequip)


********** Schemes Indiv

***** NREGA
order dummy_nregarecipientlist nregarecipientlist nregarecipientid nregarecipientname nreganberdaysworked nregaincome, after(schemesize_land)


***** Cash assistance for marriage
rename schemerecipientlist3 schemerecipientlist_cashmarriage
rename schemeyearbenefited7 schemedate_cashmarriage
rename schemeamount7 schemeamount_cashmarriage
order schemerecipientlist_cashmarriage schemedate_cashmarriage schemeamount_cashmarriage, after(nregaincome)


***** Gold for marriage
rename schemerecipientlist4 schemerecipientlist_goldmarriage
rename schemeyearbenefited8 schemedate_goldmarriage
rename schemeamount8 schemeamount_goldmarriage
order schemerecipientlist_goldmarriage schemedate_goldmarriage schemeamount_goldmarriage, after(schemeamount_cashmarriage)


***** Old age pension
rename schemerecipientlist5 schemerecipientlist_oldage
rename schemepensionamount1 schemeamount_oldage
rename schemepensionsdate1 schemedate_oldage
order schemerecipientlist_oldage schemeamount_oldage schemedate_oldage, after(schemeamount_goldmarriage)


***** Widow's pension
rename schemerecipientlist6 schemerecipientlist_widows
rename schemepensionamount2 schemeamount_widows
rename schemepensiondate2 schemedate_widows
order schemerecipientlist_widows schemeamount_widows schemedate_widows, after(schemedate_oldage)


***** National maternity
rename schemerecipientlist7 schemerecipientlist_maternity
rename schemepensionamount3 schemeamount_maternity
rename schemepensiondate3 schemedate_maternity
order schemerecipientlist_maternity schemeamount_maternity schemedate_maternity, after(schemedate_widows)



***** National disability
rename schemerecipientlist8 schemerecipientlist_disability
rename schemepensionamount4 schemeamount_disability
rename schemepensiondate4 schemedate_disability
order schemerecipientlist_disability schemeamount_disability schemedate_disability, after(schemedate_maternity)


***** Retirement pension
rename schemerecipientlist9 schemerecipientlist_retirement
rename schemepensionamount5 schemeamount_retirement
rename schemepensiondate5 schemedate_retirement
order schemerecipientlist_retirement schemeamount_retirement schemedate_retirement, after(schemedate_disability)



***** Free laptop
rename schemerecipientlist10 schemerecipientlist_laptop
rename schemepensiondate6 schemedate_laptop
rename schemepensionamount6 schemeamount_laptop
order schemerecipientlist_laptop schemedate_laptop schemeamount_laptop, after(schemedate_retirement)


***** SE --> Nobody is concerned
/*
rename schemerecipientlist11 selfemprecipientlist
rename schemepensiondate7 selfempdate
rename schemepensionamount7 selfempamount
*/




********** Clean other var
drop jatis2010_str jatis2016_str dummyego dummynewHH dummy_respondent2020 name2016 pb




********** Check what are these variables
drop numformerfamily numleftfamily parent_key_BaseAgri address_BaseAgri submissiondate_BaseAgri geopointlatitude_BaseAgri geopointlongitude_BaseAgri geopointaltitude_BaseAgri geopointaccuracy_BaseAgri villagename_BaseAgri villagearea_BaseAgri namenewhead sondaughter sondaughtername issue_new childname_modif instancename formdef_version value_householdid_2020 householdid_int




********** Parent
fre householdidparent_backup 
fre householdidparent
fre householdidparent_key
drop householdidparent_backup
order householdidparent_key, after(householdidparent)

destring newfrompanel villagenameparent villageareaparent comefrom, replace

label values newfrompanel yesno
label values comefrom yesno
label values villagenameparent villageid
label values villageareaparent villageareaid

fre villageareaparent





********** Lefthome order
order livinghome lefthomedurationlessoneyear lefthomedurationmoreoneyear lefthomedestination lefthomereason, after(interviewer)


order dummylefthousehold reasonlefthome reasonlefthomeother lefthomeid lefthomename, after(lefthousehold)

drop lefthomeid lefthomename
label values dummylefthousehold yesno




********** Religion
destring religion, replace
fre religion
rename religion religionnew
merge 1:1 HHID_panel INDID_panel using "NEEMSIS1-religion"
drop if _merge==2
drop _merge
replace religion=religionnew if religion==. & religionnew!=.

order religion, after(religionnew)
drop religionnew

sort HHID_panel INDID_panel

bysort HHID_panel: egen max_religion=max(religion)
bysort HHID_panel: egen min_religion=min(religion)
label values min_religion religion
label values max_religion religion

order min_religion max_religion, after(religion)

sort HHID_panel INDID_panel

list HHID_panel INDID_panel min_religion max_religion if religion==., clean noobs

replace religion=min_religion if religion==. & min_religion!=.
drop min_religion max_religion




********** newmembernb formermembernb
merge 1:1 HHID_panel INDID_panel using "NEEMSIS2-newformer"
drop if _merge==2
drop _merge

order formermember, after(address)
order newmembernb, before(name)

destring othermember, replace
label values othermember yesno
fre othermember



********** Villagename
ta villageid villagename
replace villagename="Elanthalmpattu" if villagename=="1"
replace villagename="Govulapuram" if villagename=="2"
replace villagename="Karumbur" if villagename=="3"
replace villagename="Korattore" if villagename=="4"
replace villagename="Kuvagam" if villagename=="5"
replace villagename="Manapakkam" if villagename=="6"
replace villagename="Manamthavizhinthaputhur" if villagename=="7"
replace villagename="Natham" if villagename=="8"
replace villagename="Oraiyure" if villagename=="9"
replace villagename="Semakottai" if villagename=="10"



********** version
order version_HH version_agri, after(submissiondate)





********** new/former HH and indiv + panel details
*** HH
merge m:1 HHID_panel using "ODRIIS-HH_wide", keepusing(HHID2010 HHID2016)
drop if _merge==2
drop _merge

gen dummyHHpanel=0
replace dummyHHpanel=1 if HHID2016!=""
replace dummyHHpanel=2 if HHID2016!="" & HHID2010!=""

label define dummyHHpanel 0"New household" 1"NEEMSIS-1 household" 2"RUME and NEEMSIS-1 household"
label values dummyHHpanel dummyHHpanel

preserve
duplicates drop HHID_panel, force
fre dummyHHpanel
dis 382+103
restore

drop HHID2010 HHID2016

gen dummynewHH=0
replace dummynewHH=1 if dummyHHpanel==0
label values dummynewHH yesno

order dummyHHpanel dummynewHH, after(version_agri)


*** Indiv
merge 1:1 HHID_panel INDID_panel using "ODRIIS-indiv_wide", keepusing(wave2010 wave2016 wave2020)
drop if _merge==2
drop _merge

gen dummyindivpanel=0
replace dummyindivpanel=1 if wave2016!=""
replace dummyindivpanel=2 if wave2016!="" & wave2010!=""

label define dummyindivpanel 0"New individual" 1"NEEMSIS-1 individual" 2"RUME and NEEMSIS-1 individual"
label values dummyindivpanel dummyindivpanel

fre dummyindivpanel
dis 1783+845

order dummyindivpanel, after(dummynewHH)
drop wave2010 wave2016 wave2020



********** dummyformermember and dummynewmember
fre formermember
fre newmember

gen dummynewmember=0
replace dummynewmember=1 if INDID_new!=.

gen dummyformermember=0
replace dummyformermember=1 if INDID_former!=.
replace dummyformermember=1 if INDID_left!=.

ta dummyformermember dummynewmember
/*

dummyforme |    dummynewmember
   rmember |         0          1 |     Total
-----------+----------------------+----------
         0 |         0      1,124 |     1,124 
         1 |     2,523          0 |     2,523 
-----------+----------------------+----------
     Total |     2,523      1,124 |     3,647 
*/




********** Correct list and id, name to avoid an excessive number of variables

foreach x in migrant remrecipient remsender borrower hhlender {
drop `x'list `x'id `x'name
rename dummy_`x' dummy`x'list
}


foreach x in recommendgiven {
drop `x'list `x'id `x'name
rename dummy_`x'list dummy`x'list
}

foreach x in chitfundbelonger savingsowner goldowner insuranceowner {
drop `x'id `x'name
rename dummy_`x'id dummy`x'list
}





********** Marriage
preserve
order HHID_panel INDID_panel name INDID2020 dummylefthousehold livinghome dummynewmember dummyformermember dummymarriage marriedlist dummy_marriedlist marriedname marriedid marriagesomeoneelse marriagedate
restore
fre marriagegiftsource marriagegiftsourcename1 marriagegiftsourcename2 marriagegiftsourcename3 marriagegiftsourcename4 marriagegiftsourcename5 marriagegiftsourcename9 marriagegiftsourcename10

foreach x in marriagegiftsourcenb marriagegifttype marriagegiftamount marriagegoldquantityasgift {
rename `x'1 `x'_WKP
rename `x'2 `x'_rela
rename `x'3 `x'_empl
rename `x'4 `x'_mais
rename `x'5 `x'_coll
rename `x'9 `x'_frie
rename `x'10 `x'_SHG
}



********** Clean scheme list

fre schemeslist
drop schemeslist
merge m:1 HHID_panel using "NEEMSIS2-HH_schemes"
drop _merge
fre schemeslist

merge m:1 HHID_panel using "NEEMSIS2-agri_schemes"
list HHID_panel if _merge==1, clean noobs
/*
GOV64-65-66-67
KUV66-67
*/
list HHID_panel if _merge==2, clean noobs
/*
GOV10-47-5-9
KUV10-25 
*/
drop if _merge==2
drop _merge

fre schemeslist schemeslist_HH

egen schemeslist_comp=concat(schemeslist schemeslist_HH), p(" ")
drop schemeslist schemeslist_HH
rename schemeslist_comp schemeslist
ta schemeslist







********** Dummy var instead list:  because c'est grave le dawa car numérotation complètement barrée !
drop schemerecipientid3 schemerecipientname3 schemerecipientid4 schemerecipientname4 schemerecipientid5 schemerecipientname5 schemerecipientid6 schemerecipientname6 schemerecipientid7 schemerecipientname7 schemerecipientid8 schemerecipientname8 schemerecipientid9 schemerecipientname9 schemerecipientid10 schemerecipientname10

rename dummy_schemerecipientlist3  dummyschemelist_cashmarriage
rename dummy_schemerecipientlist4  dummyschemelist_goldmarriage
rename dummy_schemerecipientlist5  dummyschemelist_oldage
rename dummy_schemerecipientlist6  dummyschemelist_widows
rename dummy_schemerecipientlist7  dummyschemelist_maternity
rename dummy_schemerecipientlist8  dummyschemelist_disability
rename dummy_schemerecipientlist9  dummyschemelist_retirement
rename dummy_schemerecipientlist10 dummyschemelist_laptop

rename dummy_nregarecipientlist dummyschemelist_nrega
drop nregarecipientlist nregarecipientid nregarecipientname

foreach x in cashmarriage goldmarriage oldage widows maternity disability retirement laptop {
order dummyschemelist_`x', after(schemerecipientlist_`x')
drop schemerecipientlist_`x'
}

*drop dummyschemelist_*

order schemeslist, after(noowntoilet)






********** list equipment and product
drop equipmentborrowedlist_tractor equipmentborrowedlist_bullockcar equipmentborrowedlist_harvester equipmentborrowedlist_plowingmac equipmentborrowedlist_none






********** Last
drop INDID_total INDID_former INDID_new INDID_left INDID2020
rename INDID INDID2020
rename parent_key HHID2020
rename username_str username
drop old_marriedid

order dummynewmember dummyformermember, after(newmember)
drop formermember lefthousehold

label values dummynewmember yesno
label values dummyformermember yesno

rename dummyHHpanel panelHH
rename dummyindivpanel panelindiv


********** Compress
compress





**********
preserve
drop if dummylefthousehold==1
bysort HHID_panel: egen nb=sum(1)
gen test=numfamily-nb
ta test
keep if test>0
order HHID_panel nb numfamily
restore




********** Migration setof last
drop setofmigrationgroup_o setofmigrationjobidgroup
preserve
keep HHID_panel INDID_panel setof* INDID2020 HHID2020
save"temp_NEEMSIS2-HHINDID", replace
restore
drop setof*




********** Relationshiptohead
fre relationshiptohead
*drop if dummylefthousehold==1
fre relationshiptohead
ta relationshiptohead livinghome, m
replace relationshiptohead=77 if relationshiptoheadother!=""
ta relationshiptohead livinghome, m





********** Order schemes
order ///
dummyschemelist_nrega nreganberdaysworked nregaincome ///
rationcardnber rationcardmembers rationcarduse covrationcarduse rationcardreasonnouse ///
scheme_freehouse schemedate_freehouse schemetype_freehouse schemeamount_freehouse ///
schemedate_cashfuneral schemeamount_cashfuneral ///
schemedate_freecows schemeamount_freecows ///
schemedate_freelpg schemeamount_freelpg ///
schemedate_educfees schemeamount_educfees ///
schemedate_farmequip schemeamount_farmequip ///
schemedate_land schemesize_land ///
dummyschemelist_cashmarriage schemedate_cashmarriage schemeamount_cashmarriage ///
dummyschemelist_goldmarriage schemedate_goldmarriage schemeamount_goldmarriage ///
dummyschemelist_oldage schemeamount_oldage schemedate_oldage ///
dummyschemelist_widows schemeamount_widows schemedate_widows ///
dummyschemelist_maternity schemeamount_maternity schemedate_maternity ///
dummyschemelist_disability schemeamount_disability schemedate_disability ///
dummyschemelist_retirement schemeonamount_retirement schemedate_retirement ///
schemedate_shgloan schemeamount_shgloan ///
schemedate_freepatta schemeamount_freepatta ///
dummyschemelist_laptop schemedate_laptop schemeamount_laptop ///
schemedate_girlprotection schemeamount_girlprotection, last






********** Last
order HHID2020 INDID2020
compress






********** SAVE
save"Last\NEEMSIS2-HH", replace
