cls
/*
-------------------------
Arnaud Natal
arnaud.natal@u-bordeaux.fr
September 16, 2021
-----
TITLE: Other file
-------------------------
*/

clear all
macro drop _all
cls
********** Path to folder "data" folder.
global directory = "D:\Documents\_Thesis\_DATA\NEEMSIS1"

cd"$directory"
clear all





****************************************
* Variables Arnaud
****************************************
use"NEEMSIS1-HH_v8.dta", clear


drop loanbalance_indiv loanamount_wm_indiv mean_yratepaid_indiv mean_monthlyinterestrate_indiv sum_otherlenderservices_1 sum_otherlenderservices_2 sum_otherlenderservices_3 sum_otherlenderservices_4 sum_otherlenderservices_5 sum_borrowerservices_1 sum_borrowerservices_2 sum_borrowerservices_3 sum_borrowerservices_4 sum_plantorepay_1 sum_plantorepay_2 sum_plantorepay_3 sum_plantorepay_4 sum_plantorepay_5 sum_plantorepay_6 sum_settleloanstrategy_1 sum_settleloanstrategy_2 sum_settleloanstrategy_3 sum_settleloanstrategy_4 sum_settleloanstrategy_5 sum_settleloanstrategy_6 sum_settleloanstrategy_7 sum_settleloanstrategy_8 sum_settleloanstrategy_9 sum_settleloanstrategy_10 imp1_ds_tot_HH imp1_is_tot_HH imp1_ds_tot_wm_HH imp1_is_tot_wm_HH informal_HH semiformal_HH formal_HH economic_HH current_HH humancap_HH social_HH house_HH incomegen_HH noincomegen_HH economic_amount_HH current_amount_HH humancap_amount_HH social_amount_HH house_amount_HH incomegen_amount_HH noincomegen_amount_HH informal_amount_HH formal_amount_HH semiformal_amount_HH marriageloan_HH marriageloanamount_HH dummyproblemtorepay_HH dummyhelptosettleloan_HH dummyinterest_HH loans_HH loanamount_HH loanbalance_HH loanamount_wm_HH mean_yratepaid_HH mean_monthlyinterestrate_HH sum_ext_HH

drop amountownland_as2010 amountownlandwet_as2010 assets_as2010 assets_noland remreceivedtotalamount_indiv remreceivedtotalamount_HH incomeassets_HH incomeassets_indiv otherhouserent_HH otherhouserent_indiv pension_indiv pension_HH raw_curious rr_curious raw_interestedbyart rr_interestedbyart raw_repetitivetasks rr_repetitivetasks raw_inventive rr_inventive raw_liketothink rr_liketothink raw_newideas rr_newideas raw_activeimagination rr_activeimagination raw_organized rr_organized raw_makeplans rr_makeplans raw_workhard rr_workhard raw_appointmentontime rr_appointmentontime raw_putoffduties rr_putoffduties raw_easilydistracted rr_easilydistracted raw_completeduties rr_completeduties raw_enjoypeople rr_enjoypeople raw_sharefeelings rr_sharefeelings raw_shywithpeople rr_shywithpeople raw_enthusiastic rr_enthusiastic raw_talktomanypeople rr_talktomanypeople raw_talkative rr_talkative raw_expressingthoughts rr_expressingthoughts raw_workwithother rr_workwithother raw_understandotherfeeling rr_understandotherfeeling raw_trustingofother rr_trustingofother raw_rudetoother rr_rudetoother raw_toleratefaults rr_toleratefaults raw_forgiveother rr_forgiveother raw_helpfulwithothers rr_helpfulwithothers raw_managestress rr_managestress raw_nervous rr_nervous raw_changemood rr_changemood raw_feeldepressed rr_feeldepressed raw_easilyupset rr_easilyupset raw_worryalot rr_worryalot raw_staycalm rr_staycalm raw_tryhard rr_tryhard raw_stickwithgoals rr_stickwithgoals raw_goaftergoal rr_goaftergoal raw_finishwhatbegin rr_finishwhatbegin raw_finishtasks rr_finishtasks raw_keepworking rr_keepworking ars ars2 ars3

drop imrr_curious imrr_interestedbyart imrr_repetitivetasks imrr_inventive imrr_liketothink imrr_newideas imrr_activeimagination imrr_organized imrr_makeplans imrr_workhard imrr_appointmentontime imrr_putoffduties imrr_easilydistracted imrr_completeduties imrr_enjoypeople imrr_sharefeelings imrr_shywithpeople imrr_enthusiastic imrr_talktomanypeople imrr_talkative imrr_expressingthoughts imrr_workwithother imrr_understandotherfeeling imrr_trustingofother imrr_rudetoother imrr_toleratefaults imrr_forgiveother imrr_helpfulwithothers imrr_managestress imrr_nervous imrr_changemood imrr_feeldepressed imrr_easilyupset imrr_worryalot imrr_staycalm imrr_tryhard imrr_stickwithgoals imrr_goaftergoal imrr_finishwhatbegin imrr_finishtasks imrr_keepworking imcr_curious imcr_interestedbyart imcr_repetitivetasks imcr_inventive imcr_liketothink imcr_newideas imcr_activeimagination imcr_organized imcr_makeplans imcr_workhard imcr_appointmentontime imcr_putoffduties imcr_easilydistracted imcr_completeduties imcr_enjoypeople imcr_sharefeelings imcr_shywithpeople imcr_enthusiastic imcr_talktomanypeople imcr_talkative imcr_expressingthoughts imcr_workwithother imcr_understandotherfeeling imcr_trustingofother imcr_rudetoother imcr_toleratefaults imcr_forgiveother imcr_helpfulwithothers imcr_managestress imcr_nervous imcr_changemood imcr_feeldepressed imcr_easilyupset imcr_worryalot imcr_staycalm imcr_tryhard imcr_stickwithgoals imcr_goaftergoal imcr_finishwhatbegin imcr_finishtasks imcr_keepworking

drop dummyinterest_indiv dummyhelptosettleloan_indiv dummyproblemtorepay_indiv marriageloanamount_indiv marriageloan_indiv semiformal_amount_indiv formal_amount_indiv informal_amount_indiv noincomegen_amount_indiv incomegen_amount_indiv house_amount_indiv social_amount_indiv humancap_amount_indiv current_amount_indiv economic_amount_indiv noincomegen_indiv incomegen_indiv house_indiv social_indiv humancap_indiv current_indiv economic_indiv formal_indiv semiformal_indiv informal_indiv imp1_is_tot_wm_indiv imp1_ds_tot_wm_indiv imp1_is_tot_indiv imp1_ds_tot_indiv



foreach x in curious interestedbyart repetitivetasks inventive liketothink newideas activeimagination organized makeplans workhard appointmentontime putoffduties easilydistracted completeduties enjoypeople sharefeelings shywithpeople enthusiastic talktomanypeople talkative expressingthoughts workwithother understandotherfeeling trustingofother rudetoother toleratefaults forgiveother helpfulwithothers managestress nervous changemood feeldepressed easilyupset worryalot staycalm tryhard stickwithgoals goaftergoal finishwhatbegin finishtasks keepworking {
rename `x' `x'_recode
rename `x'_old `x'
}



global arnaud occinc_indiv_agri occinc_indiv_agricasual occinc_indiv_nonagricasual occinc_indiv_nonagriregnonqual occinc_indiv_nonagriregqual occinc_indiv_selfemp occinc_indiv_nrega occinc_HH_agri occinc_HH_agricasual occinc_HH_nonagricasual occinc_HH_nonagriregnonqual occinc_HH_nonagriregqual occinc_HH_selfemp occinc_HH_nrega kowinc_indiv_agri kowinc_indiv_selfemp kowinc_indiv_sjagri kowinc_indiv_sjnonagri kowinc_indiv_uwhhnonagri kowinc_indiv_uwnonagri kowinc_indiv_uwhhagri kowinc_indiv_uwagri kowinc_HH_agri kowinc_HH_selfemp kowinc_HH_sjagri kowinc_HH_sjnonagri kowinc_HH_uwhhnonagri kowinc_HH_uwnonagri kowinc_HH_uwhhagri kowinc_HH_uwagri mainocc_kindofwork_indiv mainocc_profession_indiv mainocc_occupation_indiv mainocc_sector_indiv mainocc_hoursayear_indiv mainocc_annualincome_indiv mainocc_jobdistance_indiv mainocc_occupationname_indiv mainocc_kindofwork_HH mainocc_occupation_HH edulevel caste goldquantityamount amountownlanddry amountownlandwet amountownland livestockamount_cow livestockamount_goat livestockamount_chicken livestockamount_bullock goodtotalamount assets year totalincome_indiv totalincome_HH ra1 rab1 rb1 ra2 rab2 rb2 ra3 rab3 rb3 ra4 rab4 rb4 ra5 rab5 rb5 ra6 rab6 rb6 ra7 rab7 rb7 ra8 rab8 rb8 ra9 rab9 rb9 ra10 rab10 rb10 ra11 rab11 rb11 ra12 rab12 rb12 set_a set_ab set_b raven_tt refuse num_tt lit_tt cr_curious cr_interestedbyart cr_repetitivetasks cr_inventive cr_liketothink cr_newideas cr_activeimagination cr_organized cr_makeplans cr_workhard cr_appointmentontime cr_putoffduties cr_easilydistracted cr_completeduties cr_enjoypeople cr_sharefeelings cr_shywithpeople cr_enthusiastic cr_talktomanypeople cr_talkative cr_expressingthoughts cr_workwithother cr_understandotherfeeling cr_trustingofother cr_rudetoother cr_toleratefaults cr_forgiveother cr_helpfulwithothers cr_managestress cr_nervous cr_changemood cr_feeldepressed cr_easilyupset cr_worryalot cr_staycalm cr_tryhard cr_stickwithgoals cr_goaftergoal cr_finishwhatbegin cr_finishtasks cr_keepworking cr_OP cr_CO cr_EX cr_AG cr_ES cr_Grit OP CO EX AG ES Grit loans_indiv loanamount_indiv trustingofother_recode enjoypeople_recode curious_recode organized_recode managestress_recode interestedbyart_recode tryhard_recode workwithother_recode makeplans_recode sharefeelings_recode nervous_recode stickwithgoals_recode repetitivetasks_recode shywithpeople_recode workhard_recode changemood_recode understandotherfeeling_recode inventive_recode enthusiastic_recode feeldepressed_recode appointmentontime_recode goaftergoal_recode easilyupset_recode talktomanypeople_recode liketothink_recode finishwhatbegin_recode putoffduties_recode rudetoother_recode finishtasks_recode toleratefaults_recode worryalot_recode easilydistracted_recode keepworking_recode completeduties_recode talkative_recode newideas_recode staycalm_recode forgiveother_recode activeimagination_recode expressingthoughts_recode helpfulwithothers_recode

foreach v of varlist $arnaud {
label variable `v' `"Arnaud `: variable label `v''"'
}

order $arnaud, last
order HHID_panel HHID2016 submissiondate year



***Sort data
sort HHID_panel INDID_panel


*** Order
order HHID_panel submissiondate year INDID_panel name sex age egoid jatis address villageid


save"$directory\NEEMSIS1-HH_v9.dta", replace
save"C:\Users\Arnaud\Dropbox\RUME-NEEMSIS\NEEMSIS1\NEEMSIS1-HH_v9.dta", replace



/*

year mainoccupation_hours_indiv mainoccupation_income_indiv mainoccupation_distance_indiv mainoccupation_indiv mainoccupationname_indiv annualincome_indiv nboccupation_indiv labourincome_indiv_agri labourincome_indiv_selfemp labourincome_indiv_sjagri labourincome_indiv_sjnonagri labourincome_indiv_uwhhnonagri labourincome_indiv_uwnonagri labourincome_indiv_uwhhagri labourincome_indiv_uwagri mainoccupation_HH annualincome_HH nboccupation_HH labourincome_HH_agri labourincome_HH_selfemp labourincome_HH_sjagri labourincome_HH_sjnonagri labourincome_HH_uwhhnonagri labourincome_HH_uwnonagri labourincome_HH_uwhhagri labourincome_HH_uwagri edulevel caste goldquantityamount amountownlanddry amountownlandwet amountownland livestockamount_cow livestockamount_goat livestockamount_chicken livestockamount_bullock goodtotalamount assets totalincome_indiv totalincome_HH ra1 rab1 rb1 ra2 rab2 rb2 ra3 rab3 rb3 ra4 rab4 rb4 ra5 rab5 rb5 ra6 rab6 rb6 ra7 rab7 rb7 ra8 rab8 rb8 ra9 rab9 rb9 ra10 rab10 rb10 ra11 rab11 rb11 ra12 rab12 rb12 set_a set_ab set_b raven_tt refuse num_tt lit_tt cr_curious cr_interestedbyart cr_repetitivetasks cr_inventive cr_liketothink cr_newideas cr_activeimagination cr_organized cr_makeplans cr_workhard cr_appointmentontime cr_putoffduties cr_easilydistracted cr_completeduties cr_enjoypeople cr_sharefeelings cr_shywithpeople cr_enthusiastic cr_talktomanypeople cr_talkative cr_expressingthoughts cr_workwithother cr_understandotherfeeling cr_trustingofother cr_rudetoother cr_toleratefaults cr_forgiveother cr_helpfulwithothers cr_managestress cr_nervous cr_changemood cr_feeldepressed cr_easilyupset cr_worryalot cr_staycalm cr_tryhard cr_stickwithgoals cr_goaftergoal cr_finishwhatbegin cr_finishtasks cr_keepworking cr_OP cr_CO cr_EX cr_AG cr_ES cr_Grit OP CO EX AG ES Grit loans_indiv loanamount_indiv trustingofother_recode enjoypeople_recode curious_recode organized_recode managestress_recode interestedbyart_recode tryhard_recode workwithother_recode makeplans_recode sharefeelings_recode nervous_recode stickwithgoals_recode repetitivetasks_recode shywithpeople_recode workhard_recode changemood_recode understandotherfeeling_recode inventive_recode enthusiastic_recode feeldepressed_recode appointmentontime_recode goaftergoal_recode easilyupset_recode talktomanypeople_recode liketothink_recode finishwhatbegin_recode putoffduties_recode rudetoother_recode finishtasks_recode toleratefaults_recode worryalot_recode easilydistracted_recode keepworking_recode completeduties_recode talkative_recode newideas_recode staycalm_recode forgiveother_recode activeimagination_recode expressingthoughts_recode helpfulwithothers_recode


*/
****************************************
* END










****************************************
* Variables Arnaud
****************************************
use"NEEMSIS1-loans_v11", clear

drop submissiondate_o loan_id lender2 lender3 lender4 totalrepaid2 interestpaid2 principalpaid2 yratepaid monthlyinterestrate ratiotest loanduration_wm totalrepaid2_wm loanamount_wm loanbalance_wm interestpaid2_wm annualincome_indiv annualincome_HH debt_service debt_service_wm interest_service interest_service_wm imp_principal imp1_interest imp1_totalrepaid_year imp1_debt_service imp1_debt_service_wm imp1_interest_service imp1_interest_service_wm imp1_ds_tot_indiv imp1_is_tot_indiv imp1_ds_tot_wm_indiv imp1_is_tot_wm_indiv imp1_ds_tot_HH imp1_is_tot_HH imp1_ds_tot_wm_HH imp1_is_tot_wm_HH marriageloan marriageloanamount loans informal_indiv informal_HH semiformal_indiv semiformal_HH formal_indiv formal_HH economic_indiv economic_HH current_indiv current_HH humancap_indiv humancap_HH social_indiv social_HH house_indiv house_HH incomegen_indiv incomegen_HH noincomegen_indiv noincomegen_HH economic_amount_indiv economic_amount_HH current_amount_indiv current_amount_HH humancap_amount_indiv humancap_amount_HH social_amount_indiv social_amount_HH house_amount_indiv house_amount_HH incomegen_amount_indiv incomegen_amount_HH noincomegen_amount_indiv noincomegen_amount_HH informal_amount_indiv informal_amount_HH formal_amount_indiv formal_amount_HH semiformal_amount_indiv semiformal_amount_HH marriageloan_indiv marriageloan_HH marriageloanamount_indiv marriageloanamount_HH dummyproblemtorepay_indiv dummyproblemtorepay_HH dummyhelptosettleloan_indiv dummyhelptosettleloan_HH dummyinterest_indiv dummyinterest_HH loans_indiv loans_HH loanamount_indiv loanamount_HH loanbalance_indiv loanbalance_HH loanamount_wm_indiv loanamount_wm_HH mean_yratepaid_indiv mean_monthlyinterestrate_indiv mean_yratepaid_HH mean_monthlyinterestrate_HH otherlenderservices_1 otherlenderservices_2 otherlenderservices_3 otherlenderservices_4 otherlenderservices_5 sum_otherlenderservices_1 sum_otherlenderservices_2 sum_otherlenderservices_3 sum_otherlenderservices_4 sum_otherlenderservices_5 borrowerservices_1 borrowerservices_2 borrowerservices_3 borrowerservices_4 sum_borrowerservices_1 sum_borrowerservices_2 sum_borrowerservices_3 sum_borrowerservices_4 plantorepay_1 plantorepay_2 plantorepay_3 plantorepay_4 plantorepay_5 plantorepay_6 sum_plantorepay_1 sum_plantorepay_2 sum_plantorepay_3 sum_plantorepay_4 sum_plantorepay_5 sum_plantorepay_6 settleloanstrategy_1 settleloanstrategy_2 settleloanstrategy_3 settleloanstrategy_4 settleloanstrategy_5 settleloanstrategy_6 settleloanstrategy_7 settleloanstrategy_8 settleloanstrategy_9 settleloanstrategy_10 sum_settleloanstrategy_1 sum_settleloanstrategy_2 sum_settleloanstrategy_3 sum_settleloanstrategy_4 sum_settleloanstrategy_5 sum_settleloanstrategy_6 sum_settleloanstrategy_7 sum_settleloanstrategy_8 sum_settleloanstrategy_9 sum_settleloanstrategy_10




foreach x in dummymainloan year submissiondate loanduration informal semiformal formal economic current humancap social house incomegen noincomegen economic_amount current_amount humancap_amount social_amount house_amount incomegen_amount noincomegen_amount informal_amount formal_amount semiformal_amount {
label variable `x' `"Arnaud `: variable label `v''"'
}

save"NEEMSIS1-loans_v12", replace
save"C:\Users\Arnaud\Dropbox\RUME-NEEMSIS\NEEMSIS1\NEEMSIS1-loans_v12", replace

****************************************
* END
