/*
-------------------------
Arnaud Natal
arnaud.natal@u-bordeaux.fr
October 6, 2022
-----
CLEANING ALL LONG FILES OF NEEMSIS2
-----
-------------------------
*/



****************************************
* INITIALIZATION
****************************************
clear all
macro drop _all
cls
********** Path to folder "data" folder.
*global directory = "D:\Documents\_Thesis\_DATA\NEEMSIS2\DATA\APPEND"
global directory = "C:\Users\Arnaud\Documents\MEGA\Data\Data_NEEMSIS2_Tracking\raw\combine_new"

cd"$directory"

********** Name of the NEEMSIS2 questionnaire version to clean
*global preamble "`dbv'"
global preamble "NEEMSIS2 tracking 2022"

****************************************
* END














****************************************
* CLEAN MASTER FILE
****************************************
use"NEEMSIS2track.dta", clear


********** Drop duplicates
duplicates drop householdidoriginal migrationaddress rankingmigrantfromearlier, force


********** Clear variables
drop householdmigrantslist_1 householdmigrantslist_2 householdmigrantslist_3 householdmigrantslist_4 householdmigrantslist_5 householdmigrantslist_6 householdmigrantslist_7 householdmigrantslist_8 householdmigrantslist_9 householdmigrantslist_10 householdmigrantslist_11 householdmigrantslist_12 householdmigrantslist_13 householdmigrantslist_14 householdmigrantslist_15 householdmigrantslist_16 householdmigrantslist_17 householdmigrantslist_18 householdmigrantslist_19 householdmigrantslist_20 householdmigrantslist_21 householdmigrantslist_22 householdmigrantslist_23 householdmigrantslist_24 householdmigrantslist_25 householdmigrantslist_26 householdmigrantslist_27 householdmigrantslist_28 householdmigrantslist_29 householdmigrantslist_30 householdmigrantslist_31 householdmigrantslist_32 householdmigrantslist_33 householdmigrantslist_34 householdmigrantslist_35 householdmigrantslist_36 householdmigrantslist_37 householdmigrantslist_38 householdmigrantslist_39 householdmigrantslist_40 householdmigrantslist_41 householdmigrantslist_42 householdmigrantslist_43 householdmigrantslist_44 householdmigrantslist_45 householdmigrantslist_46 householdmigrantslist_47 householdmigrantslist_48 householdmigrantslist_49 householdmigrantslist_50 householdmigrantslist_51 householdmigrantslist_52 householdmigrantslist_53 householdmigrantslist_54 householdmigrantslist_55 householdmigrantslist_56 householdmigrantslist_57 householdmigrantslist_58 householdmigrantslist_59 householdmigrantslist_60 householdmigrantslist_61 householdmigrantslist_62 householdmigrantslist_63 householdmigrantslist_64 householdmigrantslist_65 householdmigrantslist_66 householdmigrantslist_67 householdmigrantslist_68 householdmigrantslist_69 householdmigrantslist_70 householdmigrantslist_71 householdmigrantslist_72 householdmigrantslist_73 householdmigrantslist_74 householdmigrantslist_75 householdmigrantslist_76 householdmigrantslist_77 householdmigrantslist_78 householdmigrantslist_79 householdmigrantslist_80 householdmigrantslist_81 householdmigrantslist_82 householdmigrantslist_83 householdmigrantslist_84 householdmigrantslist_85 householdmigrantslist_86 householdmigrantslist_87 householdmigrantslist_88 householdmigrantslist_89 householdmigrantslist_90 householdmigrantslist_91 householdmigrantslist_92 householdmigrantslist_93 householdmigrantslist_94 householdmigrantslist_95 householdmigrantslist_96 householdmigrantslist_97 householdmigrantslist_98 householdmigrantslist_99 householdmigrantslist_100 householdmigrantslist_101 householdmigrantslist_102 householdmigrantslist_103 householdmigrantslist_104 householdmigrantslist_105 householdmigrantslist_106 householdmigrantslist_107 householdmigrantslist_108 householdmigrantslist_109 householdmigrantslist_110 householdmigrantslist_111 householdmigrantslist_112 householdmigrantslist_113 householdmigrantslist_114 householdmigrantslist_115 householdmigrantslist_116 householdmigrantslist_117 householdmigrantslist_118 householdmigrantslist_119 householdmigrantslist_120 householdmigrantslist_121 householdmigrantslist_122 householdmigrantslist_123 householdmigrantslist_124 householdmigrantslist_125 householdmigrantslist_126 householdmigrantslist_127 householdmigrantslist_128 householdmigrantslist_129 householdmigrantslist_130 householdmigrantslist_131 householdmigrantslist_132 householdmigrantslist_133 householdmigrantslist_134 householdmigrantslist_135 householdmigrantslist_136 householdmigrantslist_137 householdmigrantslist_138 householdmigrantslist_139 householdmigrantslist_140 householdmigrantslist_141 householdmigrantslist_142 householdmigrantslist_143 householdmigrantslist_144 householdmigrantslist_145 householdmigrantslist_146 householdmigrantslist_147 householdmigrantslist_148 householdmigrantslist_149 householdmigrantslist_150 householdmigrantslist_151 householdmigrantslist_152 householdmigrantslist_153 householdmigrantslist_154 householdmigrantslist_155 householdmigrantslist_156 householdmigrantslist_157 householdmigrantslist_158 householdmigrantslist_159 householdmigrantslist_160 householdmigrantslist_161 householdmigrantslist_162 householdmigrantslist_163 householdmigrantslist_164 householdmigrantslist_165 householdmigrantslist_166 householdmigrantslist_167 householdmigrantslist_168 householdmigrantslist_169 householdmigrantslist_170 householdmigrantslist_171 householdmigrantslist_172 householdmigrantslist_173 householdmigrantslist_174 householdmigrantslist_175 householdmigrantslist_176 householdmigrantslist_177 householdmigrantslist_178 householdmigrantslist_179 householdmigrantslist_180 householdmigrantslist_181 householdmigrantslist_182 householdmigrantslist_183 householdmigrantslist_184 householdmigrantslist_185 householdmigrantslist_186 householdmigrantslist_187 householdmigrantslist_188 householdmigrantslist_189 householdmigrantslist_190 householdmigrantslist_191 householdmigrantslist_192 householdmigrantslist_193 householdmigrantslist_194 householdmigrantslist_195 householdmigrantslist_196 householdmigrantslist_197 householdmigrantslist_198 householdmigrantslist_199 householdmigrantslist_200 householdmigrantslist_201 householdmigrantslist_202 householdmigrantslist_203 householdmigrantslist_204 householdmigrantslist_205 householdmigrantslist_206 householdmigrantslist_207 householdmigrantslist_208 householdmigrantslist_209 householdmigrantslist_210 householdmigrantslist_211 householdmigrantslist_212


drop rankingmigrantfromearlier

drop landpurchasedhowbuy_1 landpurchasedhowbuy_2 landpurchasedhowbuy_3 landpurchasedhowbuy_4 landpurchasedhowbuy_5 landpurchasedhowbuy_6 landpurchasedhowbuy_7 livestocklist_1 livestocklist_2 livestocklist_3 livestocklist_4 livestocklist_5 livestocklist_6

drop drywetownland_1 drywetownland_2 listgoods_1 listgoods_2 listgoods_3 listgoods_4 listgoods_5 listgoods_6 listgoods_7 listgoods_8 listgoods_9 listgoods_10 listgoods_11 listgoods_12 listgoods_77 listgoods_13 schemeslist_1 schemeslist_2 schemeslist_3 schemeslist_4 schemeslist_5 schemeslist_6 schemeslist_7 schemeslist_8 schemeslist_9 schemeslist_10 schemeslist_11 schemeslist_12 schemeslist_13 schemeslist_14 schemeslist_15 schemeslist_16 schemeslist_17 schemeslist_18 interviewplacemig_label householdvillageoriginal_label householdidoriginal_label migrationareatype_label migrationareaurban_label migrationarearural_label householdmigrantslist_label rankingmigrant_label othermemberhhmig_label dummyownland_label ownland_label drywetownland_label landpurchased_label landpurchasedhowbuy_label livestocklist_label listgoods_label house_label housetype_label housetitle_label ownotherhouse_label electricity_label water_label toiletfacility_label noowntoilet_label schemeslist_label


********** Key and base
rename key parent_key
replace base="new" if base!="old"



********** Add details goods
preserve
use"NEEMSIS2track-detailsgoods", clear
drop if numbergoods==.
drop goodstotalamount base setofdetailsgoods key

destring goodid, replace
reshape wide goodname numbergoods goodsamount, i(parent_key) j(goodid)

foreach x in numbergoods goodsamount {
rename `x'1 `x'_car
rename `x'2 `x'_bike
rename `x'3 `x'_fridge
rename `x'4 `x'_furniture
rename `x'6 `x'_cellphone
rename `x'10 `x'_cookinggas
rename `x'11 `x'_computer
rename `x'12 `x'_dishantenna
rename `x'13 `x'_none
}

drop goodname*
save"NEEMSIS2track-detailsgoods_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-detailsgoods_v2"
drop if _merge==2
drop _merge



********** Add livestock
preserve
use"NEEMSIS2track-livestock", clear
drop if livestocknb==.
drop base setoflivestock key

destring livestockid, replace
reshape wide livestockname livestocknb livestockprice, i(parent_key) j(livestockid)

foreach x in livestocknb livestockprice {
rename `x'1 `x'_cows
rename `x'2 `x'_goats
rename `x'3 `x'_chicken
}

drop livestockname*
save"NEEMSIS2track-livestock_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-livestock_v2"
drop if _merge==2
drop _merge

order parent_key
rename parent_key HHID2022
drop geolocationlatitude geolocationlongitude geolocationaltitude geolocationaccuracy


save"NEEMSIS2-tracking_v1.dta", replace

keep HHID2022 householdidoriginal migstepmigration
gen tokeep=1

duplicates drop

save"N2track", replace
****************************************
* END










****************************************
* Migration step
****************************************
use"NEEMSIS2track-migrationstep", clear


********** Duplicates drop
rename parent_key HHID2022
destring migmigrationstepnumber, gen(migrationstepid)
order HHID2022 migrationstepid
sort HHID2022 migrationstepid


merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge

*
preserve
duplicates drop HHID2022, force
count
restore


********** Clean
drop migmigration1reason_1 migmigration1reason_2 migmigration1reason_3 migmigration1reason_4 migmigration1reason_5 migmigration1reason_6 migmigration1reason_7 migmigration1reason_8 migmigration1reason_9 migmigration1reason_10 migmigration1reason_77 migsourcemigrationcost_1 migsourcemigrationcost_2 migsourcemigrationcost_3 migsourcemigrationcost_4 migsourcemigrationcost_5 migsourcemigrationcost_66 migsourcemigrationcost_99 base migmigration1type2_label migmigration1reason_label migmigration1kindofwork_label migmigration1kindofwork2_label migsatisfaction_label migmigration1type_label migrationhelptrue_label migsndecimig_label migmigration1forced_label migsourcemigrationcost_label key setofmigmigrationstep

********** Rename
foreach x in migmigrationstepnumber migmigrationdeparture migmigrationarrival migmigration1type2 migmigration1type2other migmigration1reason migmigration1reasonother migmigration1occupationname migmigration1kindofwork migmigration1kindofwork2 migmigration1forced migmigration1cost migmigration1type {
local new=substr("`x'",4,.)
rename `x' `new'
}


save"NEEMSIS2-tracking_migpath_v1.dta", replace
*save"CLEAN\NEEMSIS2-tracking_migpath_v1.dta", replace
****************************************
* END














****************************************
* Non-migrants
****************************************
use"NEEMSIS2track-familymembers", clear


********** Clear variables
drop reasonneverattendedschool_1 reasonneverattendedschool_2 reasonneverattendedschool_3 reasonneverattendedschool_4 reasonneverattendedschool_5 reasonneverattendedschool_6 reasonneverattendedschool_7 reasonneverattendedschool_8 reasonneverattendedschool_9 reasonneverattendedschool_10 reasonneverattendedschool_11 reasonneverattendedschool_12 reasonneverattendedschool_13

drop reasondropping_1 reasondropping_2 reasondropping_3 reasondropping_4 reasondropping_5 reasondropping_6 reasondropping_7 reasondropping_8 reasondropping_9 reasondropping_10 reasondropping_11 reasondropping_12 reasondropping_13 reasondropping_14 reasondropping_77

drop migrationjoblist_1 migrationjoblist_2 migrationjoblist_3 migrationjoblist_4 migrationjoblist_5 migrationjoblist_6 migrationjoblist_7 migrationjoblist_8 migrationjoblist_9

drop base sex_label relationshiptohead_label maritalstatus_label casteindividual_label religionindividual_label dummycastespouse_label comefromspouse_label dummyreligionspouse_label religionspouse_label castespouse_label everattendedschool_label classcompleted_label currentlyatschool_label reasonneverattendedschool_label reasondropping_label dummygold_label dummyloan_label dummyworkedpastyear_label reasonnotworkpastyear_label dummymigration_label migrationjoblist_label

drop setoffamilymembers


********** Add name number
preserve
use"NEEMSIS2track-individualid", clear
drop key setofindividualid base
save"NEEMSIS2track-individualid_v2", replace
restore

rename namefromearlier name
merge 1:1 name parent_key using "NEEMSIS2track-individualid_v2"
drop if _merge==2
drop _merge

order parent_key key namenumber, first
rename parent_key HHID2022
rename key setofnonmigrants


********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop if _merge==2
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore


save"NEEMSIS2track-nonmigindiv", replace
****************************************
* END










****************************************
* Migrants
****************************************
use"NEEMSIS2track-migquestion", clear



********** Clear variables
drop migreasonneverattendedschool_1 migreasonneverattendedschool_2 migreasonneverattendedschool_3 migreasonneverattendedschool_4 migreasonneverattendedschool_5 migreasonneverattendedschool_6 migreasonneverattendedschool_7 migreasonneverattendedschool_8 migreasonneverattendedschool_9 migreasonneverattendedschool_10 migreasonneverattendedschool_11 migreasonneverattendedschool_12 migreasonneverattendedschool_13 migreasondropping_1 migreasondropping_2 migreasondropping_3 migreasondropping_4 migreasondropping_5 migreasondropping_6 migreasondropping_7 migreasondropping_8 migreasondropping_9 migreasondropping_10 migreasondropping_11 migreasondropping_12 migreasondropping_13 migreasondropping_14 migreasondropping_77 migkindofworkinactive_1 migkindofworkinactive_2 migkindofworkinactive_3 migkindofworkinactive_4 migkindofworkinactive_5 migkindofworkinactive_6 migkindofworkinactive_7 migkindofworkinactive_8 migmigrationjoblist_1 migmigrationjoblist_2 migmigrationjoblist_3 migmigrationjoblist_4 migmigrationjoblist_5 migmigrationjoblist_6 migmigrationjoblist_7 migmigrationjoblist_8 migmigrationjoblist_9 migreasondontsearchjob_1 migreasondontsearchjob_2 migreasondontsearchjob_3 migreasondontsearchjob_4 migreasondontsearchjob_5 migreasondontsearchjob_6 migreasondontsearchjob_7 migreasondontsearchjob_8 migreasondontsearchjob_9 migreasondontsearchjob_10 migreasondontsearchjob_11 migreasondontsearchjob_12 migreasondontsearchjob_13 migreasondontsearchjob_14 migreasondontsearchjob_15 migreasondontsearchjob_16 migreasondontsearchjob_77 migreasondontsearchjobsince15_1 migreasondontsearchjobsince15_2 migreasondontsearchjobsince15_3 migreasondontsearchjobsince15_4 migreasondontsearchjobsince15_5 migreasondontsearchjobsince15_6 migreasondontsearchjobsince15_7 migreasondontsearchjobsince15_8 migreasondontsearchjobsince15_9 migreasondontsearchjobsince15_10 migreasondontsearchjobsince15_11 migreasondontsearchjobsince15_12 migreasondontsearchjobsince15_13 migreasondontsearchjobsince15_14 migreasondontsearchjobsince15_15 migreasondontsearchjobsince15_16 migreasondontsearchjobsince15_77 migmethodfindjob_1 migmethodfindjob_2 migmethodfindjob_3 migmethodfindjob_4 migmethodfindjob_5 migmethodfindjob_6 migmethodfindjob_7 migmethodfindjob_8 migmethodfindjob_9 migmethodfindjob_99 migmethodfindjob_66 migmethodfindfirstjob_1 migmethodfindfirstjob_2 migmethodfindfirstjob_3 migmethodfindfirstjob_4 migmethodfindfirstjob_5 migmethodfindfirstjob_6 migmethodfindfirstjob_7 migmethodfindfirstjob_8 migmethodfindfirstjob_9 migmethodfindfirstjob_99 migmethodfindfirstjob_66 migreasonstoppedwagejob_1 migreasonstoppedwagejob_2 migreasonstoppedwagejob_3 migreasonstoppedwagejob_4 migreasonstoppedwagejob_5 migreasonstoppedwagejob_6 migreasonstoppedwagejob_7 migreasonstoppedwagejob_8 migreasonstoppedwagejob_9 migreasonstoppedwagejob_10 migreasonstoppedwagejob_11 migreasonstoppedwagejob_12 migreasonstoppedwagejob_77 migbusinesspaymentinkindlist_1 migbusinesspaymentinkindlist_2 migbusinesspaymentinkindlist_3 migbusinesspaymentinkindlist_4 migbusinesspaymentinkindlist_5 migbusinesspaymentinkindlist_6 migwagejobpaymentinkindlist_1 migwagejobpaymentinkindlist_2 migwagejobpaymentinkindlist_3 migwagejobpaymentinkindlist_4 migwagejobpaymentinkindlist_5 migwagejobpaymentinkindlist_6 migreasondontworkmore_1 migreasondontworkmore_2 migreasondontworkmore_3 migreasondontworkmore_4 migreasondontworkmore_5 migreasondontworkmore_6 migreasondontworkmore_7 migreasondontworkmore_8 migreasondontworkmore_9 migreasondontworkmore_10 migreasondontworkmore_11 migreasondontworkmore_12 migreasondontworkmore_13 associationlist_1 associationlist_2 associationlist_3 associationlist_4 associationlist_5 associationlist_6 associationlist_7 associationlist_8 associationlist_9 associationlist_10 associationlist_11 associationlist_12 associationlist_13 migsntechnicalhelpnamelist_1 migsntechnicalhelpnamelist_2 migsntechnicalhelpnamelist_3 migsntechnicalhelpnamelist_4 migsntechnicalhelpnamelist_5 migsntechnicalhelpnamelist_6 migsntechnicalhelpnamelist_7 migsntechnicalhelpnamelist_8 migsntechnicalhelpnamelist_9 migsntechnicalhelpnamelist_10 migsntechnicalhelpnamelist_11 migsntechnicalhelpnamelist_12 migsntechnicalhelpnamelist_13 migsntechnicalhelpnamelist_14 migsntechnicalhelpnamelist_15 migsntechnicalhelpnamelist_16 migsntechnicalhelpnamelist_17 migsntechnicalhelpnamelist_18 migsntechnicalhelpnamelist_19 migsntechnicalhelpnamelist_20 migsntechnicalhelpnamelist_21 migsntechnicalhelpnamelist_22 migsntechnicalhelpnamelist_23 migsntechnicalhelpnamelist_24 migsntechnicalhelpnamelist_25 migsntechnicalhelpnamelist_26 migsntechnicalhelpnamelist_27 migsntechnicalhelpnamelist_28 migsntechnicalhelpnamelist_29 migsntechnicalhelpnamelist_30 migsntechnicalhelpnamelist_31 migsntechnicalhelpnamelist_32 migsntechnicalhelpnamelist_33 migsntechnicalhelpnamelist_34 migsntechnicalhelpnamelist_35 migsntechnicalhelpnamelist_36 migsntechnicalhelpnamelist_37 migsntechnicalhelpnamelist_38 migsntechnicalhelpnamelist_39 migsntechnicalhelpnamelist_40 migsntechnicalhelpnamelist_41 migsntechnicalhelpnamelist_42 migsntechnicalhelpnamelist_43 migsntechnicalhelpnamelist_44 migsntechnicalhelpnamelist_45 migsntechnicalhelpnamelist_46 migsntechnicalhelpnamelist_47 migsntechnicalhelpnamelist_48 migsntechnicalhelpnamelist_49 migsntechnicalhelpnamelist_50 migsntechnicalhelpnamelist_51 migsntechnicalhelpnamelist_52 migsntechnicalhelpnamelist_53 migsntechnicalhelpnamelist_54 migsntechnicalhelpnamelist_55 migsntechnicalhelpnamelist_56 migsntechnicalhelpnamelist_57 migsntechnicalhelpnamelist_58 migsntechnicalhelpnamelist_59 migsntechnicalhelpnamelist_60 migsntechnicalhelpnamelist_61 migsntechnicalhelpnamelist_62 migsntechnicalhelpnamelist_63 migsntechnicalhelpnamelist_64 migsntechnicalhelpnamelist_65 migsntechnicalhelpnamelist_66 migsntechnicalhelpnamelist_67 migsntechnicalhelpnamelist_68 migsntechnicalhelpnamelist_69 migsntechnicalhelpnamelist_70 migsntechnicalhelpnamelist_71 migsntechnicalhelpnamelist_72 migsntechnicalhelpnamelist_73 migsntechnicalhelpnamelist_888 migsnentrustbusinessnamelist_1 migsnentrustbusinessnamelist_2 migsnentrustbusinessnamelist_3 migsnentrustbusinessnamelist_4 migsnentrustbusinessnamelist_5 migsnentrustbusinessnamelist_6 migsnentrustbusinessnamelist_7 migsnentrustbusinessnamelist_8 migsnentrustbusinessnamelist_9 migsnentrustbusinessnamelist_10 migsnentrustbusinessnamelist_11 migsnentrustbusinessnamelist_12 migsnentrustbusinessnamelist_13 migsnentrustbusinessnamelist_14 migsnentrustbusinessnamelist_15 migsnentrustbusinessnamelist_16 migsnentrustbusinessnamelist_17 migsnentrustbusinessnamelist_18 migsnentrustbusinessnamelist_19 migsnentrustbusinessnamelist_20 migsnentrustbusinessnamelist_21 migsnentrustbusinessnamelist_22 migsnentrustbusinessnamelist_23 migsnentrustbusinessnamelist_24 migsnentrustbusinessnamelist_25 migsnentrustbusinessnamelist_26 migsnentrustbusinessnamelist_27 migsnentrustbusinessnamelist_28 migsnentrustbusinessnamelist_29 migsnentrustbusinessnamelist_30 migsnentrustbusinessnamelist_31 migsnentrustbusinessnamelist_32 migsnentrustbusinessnamelist_33 migsnentrustbusinessnamelist_34 migsnentrustbusinessnamelist_35 migsnentrustbusinessnamelist_36 migsnentrustbusinessnamelist_37 migsnentrustbusinessnamelist_38 migsnentrustbusinessnamelist_39 migsnentrustbusinessnamelist_40 migsnentrustbusinessnamelist_41 migsnentrustbusinessnamelist_42 migsnentrustbusinessnamelist_43 migsnentrustbusinessnamelist_44 migsnentrustbusinessnamelist_45 migsnentrustbusinessnamelist_46 migsnentrustbusinessnamelist_47 migsnentrustbusinessnamelist_48 migsnentrustbusinessnamelist_49 migsnentrustbusinessnamelist_50 migsnentrustbusinessnamelist_51 migsnentrustbusinessnamelist_52 migsnentrustbusinessnamelist_53 migsnentrustbusinessnamelist_54 migsnentrustbusinessnamelist_55 migsnentrustbusinessnamelist_56 migsnentrustbusinessnamelist_57 migsnentrustbusinessnamelist_58 migsnentrustbusinessnamelist_59 migsnentrustbusinessnamelist_60 migsnentrustbusinessnamelist_61 migsnentrustbusinessnamelist_62 migsnentrustbusinessnamelist_63 migsnentrustbusinessnamelist_64 migsnentrustbusinessnamelist_65 migsnentrustbusinessnamelist_66 migsnentrustbusinessnamelist_67 migsnentrustbusinessnamelist_68 migsnentrustbusinessnamelist_69 migsnentrustbusinessnamelist_70 migsnentrustbusinessnamelist_71 migsnentrustbusinessnamelist_72 migsnentrustbusinessnamelist_73 migsnentrustbusinessnamelist_888 migsnrecruitworkernamelist_1 migsnrecruitworkernamelist_2 migsnrecruitworkernamelist_3 migsnrecruitworkernamelist_4 migsnrecruitworkernamelist_5 migsnrecruitworkernamelist_6 migsnrecruitworkernamelist_7 migsnrecruitworkernamelist_8 migsnrecruitworkernamelist_9 migsnrecruitworkernamelist_10 migsnrecruitworkernamelist_11 migsnrecruitworkernamelist_12 migsnrecruitworkernamelist_13 migsnrecruitworkernamelist_14 migsnrecruitworkernamelist_15 migsnrecruitworkernamelist_16 migsnrecruitworkernamelist_17 migsnrecruitworkernamelist_18 migsnrecruitworkernamelist_19 migsnrecruitworkernamelist_20 migsnrecruitworkernamelist_21 migsnrecruitworkernamelist_22 migsnrecruitworkernamelist_23 migsnrecruitworkernamelist_24 migsnrecruitworkernamelist_25 migsnrecruitworkernamelist_26 migsnrecruitworkernamelist_27 migsnrecruitworkernamelist_28 migsnrecruitworkernamelist_29 migsnrecruitworkernamelist_30 migsnrecruitworkernamelist_31 migsnrecruitworkernamelist_32 migsnrecruitworkernamelist_33 migsnrecruitworkernamelist_34 migsnrecruitworkernamelist_35 migsnrecruitworkernamelist_36 migsnrecruitworkernamelist_37 migsnrecruitworkernamelist_38 migsnrecruitworkernamelist_39 migsnrecruitworkernamelist_40 migsnrecruitworkernamelist_41 migsnrecruitworkernamelist_42 migsnrecruitworkernamelist_43 migsnrecruitworkernamelist_44 migsnrecruitworkernamelist_45 migsnrecruitworkernamelist_46 migsnrecruitworkernamelist_47 migsnrecruitworkernamelist_48 migsnrecruitworkernamelist_49 migsnrecruitworkernamelist_50 migsnrecruitworkernamelist_51 migsnrecruitworkernamelist_52 migsnrecruitworkernamelist_53 migsnrecruitworkernamelist_54 migsnrecruitworkernamelist_55 migsnrecruitworkernamelist_56 migsnrecruitworkernamelist_57 migsnrecruitworkernamelist_58 migsnrecruitworkernamelist_59 migsnrecruitworkernamelist_60 migsnrecruitworkernamelist_61 migsnrecruitworkernamelist_62 migsnrecruitworkernamelist_63 migsnrecruitworkernamelist_64 migsnrecruitworkernamelist_65 migsnrecruitworkernamelist_66 migsnrecruitworkernamelist_67 migsnrecruitworkernamelist_68 migsnrecruitworkernamelist_69 migsnrecruitworkernamelist_70 migsnrecruitworkernamelist_71 migsnrecruitworkernamelist_72 migsnrecruitworkernamelist_73 migsnrecruitworkernamelist_888 migsnfindsuppliersnamelist_1 migsnfindsuppliersnamelist_2 migsnfindsuppliersnamelist_3 migsnfindsuppliersnamelist_4 migsnfindsuppliersnamelist_5 migsnfindsuppliersnamelist_6 migsnfindsuppliersnamelist_7 migsnfindsuppliersnamelist_8 migsnfindsuppliersnamelist_9 migsnfindsuppliersnamelist_10 migsnfindsuppliersnamelist_11 migsnfindsuppliersnamelist_12 migsnfindsuppliersnamelist_13 migsnfindsuppliersnamelist_14 migsnfindsuppliersnamelist_15 migsnfindsuppliersnamelist_16 migsnfindsuppliersnamelist_17 migsnfindsuppliersnamelist_18 migsnfindsuppliersnamelist_19 migsnfindsuppliersnamelist_20 migsnfindsuppliersnamelist_21 migsnfindsuppliersnamelist_22 migsnfindsuppliersnamelist_23 migsnfindsuppliersnamelist_24 migsnfindsuppliersnamelist_25 migsnfindsuppliersnamelist_26 migsnfindsuppliersnamelist_27 migsnfindsuppliersnamelist_28 migsnfindsuppliersnamelist_29 migsnfindsuppliersnamelist_30 migsnfindsuppliersnamelist_31 migsnfindsuppliersnamelist_32 migsnfindsuppliersnamelist_33 migsnfindsuppliersnamelist_34 migsnfindsuppliersnamelist_35 migsnfindsuppliersnamelist_36 migsnfindsuppliersnamelist_37 migsnfindsuppliersnamelist_38 migsnfindsuppliersnamelist_39 migsnfindsuppliersnamelist_40 migsnfindsuppliersnamelist_41 migsnfindsuppliersnamelist_42 migsnfindsuppliersnamelist_43 migsnfindsuppliersnamelist_44 migsnfindsuppliersnamelist_45 migsnfindsuppliersnamelist_46 migsnfindsuppliersnamelist_47 migsnfindsuppliersnamelist_48 migsnfindsuppliersnamelist_49 migsnfindsuppliersnamelist_50 migsnfindsuppliersnamelist_51 migsnfindsuppliersnamelist_52 migsnfindsuppliersnamelist_53 migsnfindsuppliersnamelist_54 migsnfindsuppliersnamelist_55 migsnfindsuppliersnamelist_56 migsnfindsuppliersnamelist_57 migsnfindsuppliersnamelist_58 migsnfindsuppliersnamelist_59 migsnfindsuppliersnamelist_60 migsnfindsuppliersnamelist_61 migsnfindsuppliersnamelist_62 migsnfindsuppliersnamelist_63 migsnfindsuppliersnamelist_64 migsnfindsuppliersnamelist_65 migsnfindsuppliersnamelist_66 migsnfindsuppliersnamelist_67 migsnfindsuppliersnamelist_68 migsnfindsuppliersnamelist_69 migsnfindsuppliersnamelist_70 migsnfindsuppliersnamelist_71 migsnfindsuppliersnamelist_72 migsnfindsuppliersnamelist_73 migsnfindsuppliersnamelist_888 migsnlendtoolsnamelist_1 migsnlendtoolsnamelist_2 migsnlendtoolsnamelist_3 migsnlendtoolsnamelist_4 migsnlendtoolsnamelist_5 migsnlendtoolsnamelist_6 migsnlendtoolsnamelist_7 migsnlendtoolsnamelist_8 migsnlendtoolsnamelist_9 migsnlendtoolsnamelist_10 migsnlendtoolsnamelist_11 migsnlendtoolsnamelist_12 migsnlendtoolsnamelist_13 migsnlendtoolsnamelist_14 migsnlendtoolsnamelist_15 migsnlendtoolsnamelist_16 migsnlendtoolsnamelist_17 migsnlendtoolsnamelist_18 migsnlendtoolsnamelist_19 migsnlendtoolsnamelist_20 migsnlendtoolsnamelist_21 migsnlendtoolsnamelist_22 migsnlendtoolsnamelist_23 migsnlendtoolsnamelist_24 migsnlendtoolsnamelist_25 migsnlendtoolsnamelist_26 migsnlendtoolsnamelist_27 migsnlendtoolsnamelist_28 migsnlendtoolsnamelist_29 migsnlendtoolsnamelist_30 migsnlendtoolsnamelist_31 migsnlendtoolsnamelist_32 migsnlendtoolsnamelist_33 migsnlendtoolsnamelist_34 migsnlendtoolsnamelist_35 migsnlendtoolsnamelist_36 migsnlendtoolsnamelist_37 migsnlendtoolsnamelist_38 migsnlendtoolsnamelist_39 migsnlendtoolsnamelist_40 migsnlendtoolsnamelist_41 migsnlendtoolsnamelist_42 migsnlendtoolsnamelist_43 migsnlendtoolsnamelist_44 migsnlendtoolsnamelist_45 migsnlendtoolsnamelist_46 migsnlendtoolsnamelist_47 migsnlendtoolsnamelist_48 migsnlendtoolsnamelist_49 migsnlendtoolsnamelist_50 migsnlendtoolsnamelist_51 migsnlendtoolsnamelist_52 migsnlendtoolsnamelist_53 migsnlendtoolsnamelist_54 migsnlendtoolsnamelist_55 migsnlendtoolsnamelist_56 migsnlendtoolsnamelist_57 migsnlendtoolsnamelist_58 migsnlendtoolsnamelist_59 migsnlendtoolsnamelist_60 migsnlendtoolsnamelist_61 migsnlendtoolsnamelist_62 migsnlendtoolsnamelist_63 migsnlendtoolsnamelist_64 migsnlendtoolsnamelist_65 migsnlendtoolsnamelist_66 migsnlendtoolsnamelist_67 migsnlendtoolsnamelist_68 migsnlendtoolsnamelist_69 migsnlendtoolsnamelist_70 migsnlendtoolsnamelist_71 migsnlendtoolsnamelist_72 migsnlendtoolsnamelist_73 migsnlendtoolsnamelist_888 migsnfindjobnamelist_1 migsnfindjobnamelist_2 migsnfindjobnamelist_3 migsnfindjobnamelist_4 migsnfindjobnamelist_5 migsnfindjobnamelist_6 migsnfindjobnamelist_7 migsnfindjobnamelist_8 migsnfindjobnamelist_9 migsnfindjobnamelist_10 migsnfindjobnamelist_11 migsnfindjobnamelist_12 migsnfindjobnamelist_13 migsnfindjobnamelist_14 migsnfindjobnamelist_15 migsnfindjobnamelist_16 migsnfindjobnamelist_17 migsnfindjobnamelist_18 migsnfindjobnamelist_19 migsnfindjobnamelist_20 migsnfindjobnamelist_21 migsnfindjobnamelist_22 migsnfindjobnamelist_23 migsnfindjobnamelist_24 migsnfindjobnamelist_25 migsnfindjobnamelist_26 migsnfindjobnamelist_27 migsnfindjobnamelist_28 migsnfindjobnamelist_29 migsnfindjobnamelist_30 migsnfindjobnamelist_31 migsnfindjobnamelist_32 migsnfindjobnamelist_33 migsnfindjobnamelist_34 migsnfindjobnamelist_35 migsnfindjobnamelist_36 migsnfindjobnamelist_37 migsnfindjobnamelist_38 migsnfindjobnamelist_39 migsnfindjobnamelist_40 migsnfindjobnamelist_41 migsnfindjobnamelist_42 migsnfindjobnamelist_43 migsnfindjobnamelist_44 migsnfindjobnamelist_45 migsnfindjobnamelist_46 migsnfindjobnamelist_47 migsnfindjobnamelist_48 migsnfindjobnamelist_49 migsnfindjobnamelist_50 migsnfindjobnamelist_51 migsnfindjobnamelist_52 migsnfindjobnamelist_53 migsnfindjobnamelist_54 migsnfindjobnamelist_55 migsnfindjobnamelist_56 migsnfindjobnamelist_57 migsnfindjobnamelist_58 migsnfindjobnamelist_59 migsnfindjobnamelist_60 migsnfindjobnamelist_61 migsnfindjobnamelist_62 migsnfindjobnamelist_63 migsnfindjobnamelist_64 migsnfindjobnamelist_65 migsnfindjobnamelist_66 migsnfindjobnamelist_67 migsnfindjobnamelist_68 migsnfindjobnamelist_69 migsnfindjobnamelist_70 migsnfindjobnamelist_71 migsnfindjobnamelist_72 migsnfindjobnamelist_73 migsnfindjobnamelist_888 migsnrecommendforjobnamelist_1 migsnrecommendforjobnamelist_2 migsnrecommendforjobnamelist_3 migsnrecommendforjobnamelist_4 migsnrecommendforjobnamelist_5 migsnrecommendforjobnamelist_6 migsnrecommendforjobnamelist_7 migsnrecommendforjobnamelist_8 migsnrecommendforjobnamelist_9 migsnrecommendforjobnamelist_10 migsnrecommendforjobnamelist_11 migsnrecommendforjobnamelist_12 migsnrecommendforjobnamelist_13 migsnrecommendforjobnamelist_14 migsnrecommendforjobnamelist_15 migsnrecommendforjobnamelist_16 migsnrecommendforjobnamelist_17 migsnrecommendforjobnamelist_18 migsnrecommendforjobnamelist_19 migsnrecommendforjobnamelist_20 migsnrecommendforjobnamelist_21 migsnrecommendforjobnamelist_22 migsnrecommendforjobnamelist_23 migsnrecommendforjobnamelist_24 migsnrecommendforjobnamelist_25 migsnrecommendforjobnamelist_26 migsnrecommendforjobnamelist_27 migsnrecommendforjobnamelist_28 migsnrecommendforjobnamelist_29 migsnrecommendforjobnamelist_30 migsnrecommendforjobnamelist_31 migsnrecommendforjobnamelist_32 migsnrecommendforjobnamelist_33 migsnrecommendforjobnamelist_34 migsnrecommendforjobnamelist_35 migsnrecommendforjobnamelist_36 migsnrecommendforjobnamelist_37 migsnrecommendforjobnamelist_38 migsnrecommendforjobnamelist_39 migsnrecommendforjobnamelist_40 migsnrecommendforjobnamelist_41 migsnrecommendforjobnamelist_42 migsnrecommendforjobnamelist_43 migsnrecommendforjobnamelist_44 migsnrecommendforjobnamelist_45 migsnrecommendforjobnamelist_46 migsnrecommendforjobnamelist_47 migsnrecommendforjobnamelist_48 migsnrecommendforjobnamelist_49 migsnrecommendforjobnamelist_50 migsnrecommendforjobnamelist_51 migsnrecommendforjobnamelist_52 migsnrecommendforjobnamelist_53 migsnrecommendforjobnamelist_54 migsnrecommendforjobnamelist_55 migsnrecommendforjobnamelist_56 migsnrecommendforjobnamelist_57 migsnrecommendforjobnamelist_58 migsnrecommendforjobnamelist_59 migsnrecommendforjobnamelist_60 migsnrecommendforjobnamelist_61 migsnrecommendforjobnamelist_62 migsnrecommendforjobnamelist_63 migsnrecommendforjobnamelist_64 migsnrecommendforjobnamelist_65 migsnrecommendforjobnamelist_66 migsnrecommendforjobnamelist_67 migsnrecommendforjobnamelist_68 migsnrecommendforjobnamelist_69 migsnrecommendforjobnamelist_70 migsnrecommendforjobnamelist_71 migsnrecommendforjobnamelist_72 migsnrecommendforjobnamelist_73 migsnrecommendforjobnamelist_888 migsnrecojobsuccessnamelist_1 migsnrecojobsuccessnamelist_2 migsnrecojobsuccessnamelist_3 migsnrecojobsuccessnamelist_4 migsnrecojobsuccessnamelist_5 migsnrecojobsuccessnamelist_6 migsnrecojobsuccessnamelist_7 migsnrecojobsuccessnamelist_8 migsnrecojobsuccessnamelist_9 migsnrecojobsuccessnamelist_10 migsnrecojobsuccessnamelist_11 migsnrecojobsuccessnamelist_12 migsnrecojobsuccessnamelist_13 migsnrecojobsuccessnamelist_14 migsnrecojobsuccessnamelist_15 migsnrecojobsuccessnamelist_16 migsnrecojobsuccessnamelist_17 migsnrecojobsuccessnamelist_18 migsnrecojobsuccessnamelist_19 migsnrecojobsuccessnamelist_20 migsnrecojobsuccessnamelist_21 migsnrecojobsuccessnamelist_22 migsnrecojobsuccessnamelist_23 migsnrecojobsuccessnamelist_24 migsnrecojobsuccessnamelist_25 migsnrecojobsuccessnamelist_26 migsnrecojobsuccessnamelist_27 migsnrecojobsuccessnamelist_28 migsnrecojobsuccessnamelist_29 migsnrecojobsuccessnamelist_30 migsnrecojobsuccessnamelist_31 migsnrecojobsuccessnamelist_32 migsnrecojobsuccessnamelist_33 migsnrecojobsuccessnamelist_34 migsnrecojobsuccessnamelist_35 migsnrecojobsuccessnamelist_36 migsnrecojobsuccessnamelist_37 migsnrecojobsuccessnamelist_38 migsnrecojobsuccessnamelist_39 migsnrecojobsuccessnamelist_40 migsnrecojobsuccessnamelist_41 migsnrecojobsuccessnamelist_42 migsnrecojobsuccessnamelist_43 migsnrecojobsuccessnamelist_44 migsnrecojobsuccessnamelist_45 migsnrecojobsuccessnamelist_46 migsnrecojobsuccessnamelist_47 migsnrecojobsuccessnamelist_48 migsnrecojobsuccessnamelist_49 migsnrecojobsuccessnamelist_50 migsnrecojobsuccessnamelist_51 migsnrecojobsuccessnamelist_52 migsnrecojobsuccessnamelist_53 migsnrecojobsuccessnamelist_54 migsnrecojobsuccessnamelist_55 migsnrecojobsuccessnamelist_56 migsnrecojobsuccessnamelist_57 migsnrecojobsuccessnamelist_58 migsnrecojobsuccessnamelist_59 migsnrecojobsuccessnamelist_60 migsnrecojobsuccessnamelist_61 migsnrecojobsuccessnamelist_62 migsnrecojobsuccessnamelist_63 migsnrecojobsuccessnamelist_64 migsnrecojobsuccessnamelist_65 migsnrecojobsuccessnamelist_66 migsnrecojobsuccessnamelist_67 migsnrecojobsuccessnamelist_68 migsnrecojobsuccessnamelist_69 migsnrecojobsuccessnamelist_70 migsnrecojobsuccessnamelist_71 migsnrecojobsuccessnamelist_72 migsnrecojobsuccessnamelist_73 migsnrecojobsuccessnamelist_888 migsex_label migcaste_label migreligion_label migrelationshiptohead_label migmaritalstatus_label migdummycastespouse_label migcomefromspouse_label migdummyreligionspouse_label migreligionspouse_label migcastespouse_label migcanread_label migeverattendedschool_label migclasscompleted_label migafter10thstandard_label migdurationafter10th_label migtypeofhigheredu_label migsubjectsafter10th_label migcurrentlyatschool_label migreasonneverattendedschool_lab migreasondropping_label migdummyscholarship_label migconverseinenglish_label migdummygold_label migdummyloan_label migdummyworkedpastyear_label migreasonnotworkpastyear_label migstoppedworking_label migworkpastsixmonth_label migeverworksalaried_label migkindofworkinactive_label migdummymigration_label migmigrationjoblist_label migeverwork_label migworkpastsevendays_label migsearchjob_label migstartbusiness_label migreasondontsearchjob_label migsearchjobsince15_label migbusinessafter15_label migreasondontsearchjobsince15_la mignbermonthsearchjob_label migreadystartjob_label migmethodfindjob_label migjobpreference_label migmoveoutsideforjob_label migkindofworkfirstjob_label migmethodfindfirstjob_label migdummymainoccupation2_label migdummyseasonalmainoccup_label migselected_months_label migbeforemainoccup_label migmainoccuptype_label migmainoccuptype2_label migdummypreviouswagejob_label migpreviousjobcontract_label migreasonstoppedwagejob_label migrespect_label migworkmate_label miguseknowledgeatwork_label migsatisfactionprogress_label migsatisfyingpurpose_label migschedule_label migtakeholiday_label migagreementatwork1_label migagreementatwork2_label migagreementatwork3_label migagreementatwork4_label migchangework_label mighappywork_label migsatisfactionsalary_label migexecutionwork1_label migexecutionwork2_label migexecutionwork3_label migexecutionwork4_label migexecutionwork5_label migexecutionwork6_label migexecutionwork7_label migexecutionwork8_label migexecutionwork9_label migexecutionwork10_label migaccidentalinjury_label miglosswork_label migmostseriousincident_label migmostseriousinjury_label migphysicalharm_label migproblemwork1_label migproblemwork2_label migproblemwork3_label migproblemwork4_label migproblemwork5_label migproblemwork6_label migproblemwork7_label migproblemwork8_label migproblemwork9_label migworkexposure1_label migworkexposure2_label migworkexposure3_label migworkexposure4_label migworkexposure5_label mighearworker_label migprofessionalequipment_label migbreak_label migretirementwork_label migverbalaggression_label migphysicalagression_label migsexualharassment_label migsexualaggression_label migdiscrimination1_label migdiscrimination2_label migdiscrimination3_label migdiscrimination4_label migdiscrimination5_label migdiscrimination6_label migdiscrimination7_label migdiscrimination8_label migdiscrimination9_label migresdiscrimination1_label migresdiscrimination2_label migresdiscrimination3_label migresdiscrimination4_label migresdiscrimination5_label migrurallocation_label miglackskill_label decisionwork_label decisionearnwork_label opinionworkingwoman_label opinionactivewoman_label migbusinessnbworkers_label migdummybusinessunpaidworkers_la migbusinessnbunpaidworkers_label migdummybusinesspaidworkers_labe migbusinessnbpaidworkers_label v451 migfrequencygrossreceipt_label migbusinesssocialsecurity_label migbusinesspaymentinkind_label migbusinesspaymentinkindlist_lab migwagejobemployer_label migwagejobnbworkers_label migcontract_label migwagejobtype_label migwagejobsocialsecurity_label migdummysalary_label migjobwagefrequencycash_label migwagejobpaymentinkind_label migwagejobpaymentinkindlist_labe setofmigwagejobpaymentinkindgrou migdummyaspirationmorehours_labe migreasondontworkmore_label migdummyremittancessent_label migcompulsoryremittances_label migdummyremittancesreceived_labe setofmigremittancesreceivedsourc associationlist_label migsntechnicalhelp_label migsntechnicalhelpnamelist_label setofmigsntechnicalhelpid setofmigsntechnicalhelpgroup migsnentrustbusiness_label migsnentrustbusinessnamelist_lab migsnrecruitworker_label migsnrecruitworkernamelist_label setofmigsnrecruitworkerid setofmigsnrecruitworkergroup migsnfindsuppliers_label migsnfindsuppliersnamelist_label migsnlendtools_label migsnlendtoolsnamelist_label migsnfindjob_label migsnfindjobnamelist_label migsnrecommendforjob_label migsnrecommendforjobnamelist_lab migsnrecojobsuccess_label migsnrecojobsuccessnamelist_labe mignbercontactphone_label migcontactlist_label migdummycontactleaders_label mignetworktrustneighborhood_labe mignetworktrustemployees_label mignetworkpeoplehelping_label mignetworkhelpkinmember_label miga1_label miga2_label miga3_label miga4_label miga5_label miga6_label miga7_label miga8_label miga9_label miga10_label miga11_label miga12_label migb1_label migb2_label migb3_label migb4_label migb5_label migb6_label migb7_label migb8_label migb9_label migb10_label migb11_label migb12_label migenjoypeople_label migcurious_label migorganized_label migmanagestress_label miginterestedbyart_label migtryhard_label migworkwithother_label migmakeplans_label migsharefeelings_label mignervous_label migstickwithgoals_label migrepetitivetasks_label migshywithpeople_label migworkhard_label migchangemood_label migunderstandotherfeeling_label miginventive_label migenthusiastic_label migfeeldepressed_label migappointmentontime_label migtrustingofother_label miggoaftergoal_label migeasilyupset_label migtalktomanypeople_label migliketothink_label migfinishwhatbegin_label migputoffduties_label migrudetoother_label migfinishtasks_label migtoleratefaults_label migworryalot_label migeasilydistracted_label migkeepworking_label migcompleteduties_label migtalkative_label mignewideas_label migstaycalm_label migforgiveother_label migactiveimagination_label migexpressingthoughts_label mighelpfulwithothers_label migcanreadcard1a_label migcanreadcard1b_label migcanreadcard1c_label migcanreadcard2_label mignumeracy1_label mignumeracy2_label mignumeracy3_label mignumeracy4_label miglocuscontrol1_label miglocuscontrol2_label miglocuscontrol3_label miglocuscontrol4_label miglocuscontrol5_label miglocuscontrol6_label migab1_label migab2_label migab3_label migab4_label migab5_label migab6_label migab7_label migab8_label migab9_label migab10_label migab11_label migab12_label


********** Rename
foreach x in migindex mighouseholdmigrantslistid migname migsex migage migcaste migreligion migrelationshiptohead migmaritalstatus migcasteother migreligionother migrelationshiptoheadother mighusbandspousename migdummycastespouse migcomefromspouse migdummyreligionspouse migreligionspouse migcastespouse migotheroriginspouse migcanread migeverattendedschool migclasscompleted migafter10thstandard migdurationafter10th migtypeofhigheredu migsubjectsafter10th migothersubjectsafter10th migcurrentlyatschool migeducationexpenses migamountschoolfees migbookscost migtransportcost migreasonneverattendedschool migreasondropping migotherreasondroppingschool migotherreasonneverattendedschoo migdummyscholarship migscholarshipamount migscholarshipduration migconverseinenglish migdummygold miggoldquantity migdummyloan migtotalloanamount migdummyworkedpastyear migreasonnotworkpastyear migreasonnotworkpastyearother migstoppedworking migworkpastsixmonth migeverworksalaried migkindofworkinactive migdummymigration migmigrationjoblist migmigrationjobidgroup_count migeverwork migworkpastsevendays migsearchjob migstartbusiness migreasondontsearchjob migsearchjobsince15 migbusinessafter15 migreasondontsearchjobsince15 mignbermonthsearchjob migreadystartjob migmethodfindjob migjobpreference migmoveoutsideforjob migmoveoutsideforjobreason migaspirationminimumwage migkindofworkfirstjob migunpaidinbusinessfirstjob migagestartworking migagestartworkingpaidjob migmethodfindfirstjob migothermethodfindfirstjob migmonthstofindjob migmaxhoursayear migselected_occupposition migselected_occupname migdummymainoccupation2 migothermainoccupation2 migmainoccupation migdummyseasonalmainoccup migselected_months migselected_months_1 migselected_months_2 migselected_months_3 migselected_months_4 migselected_months_5 migselected_months_6 migselected_months_7 migselected_months_8 migselected_months_9 migselected_months_10 migselected_months_11 migselected_months_12 migindoccupmonths_count miginddaysayear2 migindhoursaday2 migindhoursayear1 migindhoursayear2 migindhoursayear migbeforemainoccup migotherbeforemainoccup migmainoccuptype migmainoccuptype2 migdummypreviouswagejob migpreviousjobcontract migreasonstoppedwagejob migotherreasonstoppedjob migrespect migworkmate miguseknowledgeatwork migsatisfactionprogress migsatisfyingpurpose migschedule migtakeholiday migagreementatwork1 migagreementatwork2 migagreementatwork3 migagreementatwork4 migchangework mighappywork migsatisfactionsalary migexecutionwork1 migexecutionwork2 migexecutionwork3 migexecutionwork4 migexecutionwork5 migexecutionwork6 migexecutionwork7 migexecutionwork8 migexecutionwork9 migexecutionwork10 migaccidentalinjury miglosswork miglossworknumber migmostseriousincident migmostseriousinjury migseriousinjuryother migphysicalharm migproblemwork1 migproblemwork2 migproblemwork3 migproblemwork4 migproblemwork5 migproblemwork6 migproblemwork7 migproblemwork8 migproblemwork9 migworkexposure1 migworkexposure2 migworkexposure3 migworkexposure4 migworkexposure5 mighearworker migprofessionalequipment migbreak migretirementwork migverbalaggression migphysicalagression migsexualharassment migsexualaggression migdiscrimination1 migdiscrimination2 migdiscrimination3 migdiscrimination4 migdiscrimination5 migdiscrimination6 migdiscrimination7 migdiscrimination8 migdiscrimination9 migresdiscrimination1 migresdiscrimination2 migresdiscrimination3 migresdiscrimination4 migresdiscrimination5 migrurallocation miglackskill migbusinessnbworkers migdummybusinessunpaidworkers migbusinessnbunpaidworkers migbusinessnbfamilyworkers migdummybusinesspaidworkers migbusinessnbpaidworkers migbusinessworkersfrequencypayme migbusinesslaborcost migfrequencygrossreceipt migamountgrossreceipt migbusinessfixedcosts migbusinessfixedcostsamount migbusinessexpenses migbusinesssocialsecurity migbusinesspaymentinkind migbusinesspaymentinkindlist migbusinesspaymentinkindgroup_co migotherwagejobemployer migwagejobnbworkers migcontract migwagejobtype migwagejobsocialsecurity migdummysalary migjobwagefrequencycash migjobwageamountcash migwagejobpaymentinkind migwagejobpaymentinkindlist migwagejobpaymentinkindgroup_cou migdummyaspirationmorehours migreasondontworkmore migaspirationminimumwage2 migdummyremittancessent migcompulsoryremittances migdummyremittancesreceived migformalsocialcapital_count migsnrecommendassoname1 migsnrecommendassoname2 migsnrecommendassoname3 migsnrecommendassoname4 migsnrecommendassoname5 migsnrecommendassoname6 migsnrecommendassoname7 migsnrecommendassoname8 migsnrecommendassoname9 migsnrecommendassoname10 migsnrecommendassoname11 migsnrecommendassoname12 migsnrecommendassoname13 migsnrecommendassoname14 migsnrecommendassoname15 migsnrecommendassoname16 migsnrecommendassoname17 migsnrecommendassoname18 migsnrecommendassoname19 migsnrecommendassoname20 migsnrecommendassoname21 migsnrecommendassoname22 migsnrecommendassoname23 migsnrecommendassoname24 migsntechnicalhelp migsntechnicalhelpnamelist migsntechnicalhelpname1 migsntechnicalhelpname2 migsntechnicalhelpname3 migsntechnicalhelpname4 migsntechnicalhelpname5 migsntechnicalhelpname6 migsntechnicalhelpname7 migsntechnicalhelpgroup_count migsnentrustbusiness migsnentrustbusinessnamelist migsnentrustbusinessname1 migsnentrustbusinessname2 migsnentrustbusinessname3 migsnentrustbusinessname4 migsnentrustbusinessname5 migsnentrustbusinessname6 migsnentrustbusinessname7 migsnentrustbusinessgroup_count migsnrecruitworker migsnrecruitworkernamelist migsnrecruitworkername1 migsnrecruitworkername2 migsnrecruitworkername3 migsnrecruitworkername4 migsnrecruitworkername5 migsnrecruitworkername6 migsnrecruitworkername7 migsnrecruitworkergroup_count migsnfindsuppliers migsnfindsuppliersnamelist migsnfindsuppliersname1 migsnfindsuppliersname2 migsnfindsuppliersname3 migsnfindsuppliersname4 migsnfindsuppliersname5 migsnfindsuppliersname6 migsnfindsuppliersname7 migsnfindsuppliersgroup_count migsnlendtools migsnlendtoolsnamelist migsnlendtoolsname1 migsnlendtoolsname2 migsnlendtoolsname3 migsnlendtoolsname4 migsnlendtoolsname5 migsnlendtoolsname6 migsnlendtoolsname7 migmigsnlendtoolsgroup_count migsnfindjob migsnfindjobnamelist migsnfindjobname1 migsnfindjobname2 migsnfindjobname3 migsnfindjobname4 migsnfindjobname5 migsnfindjobname6 migsnfindjobname7 migsnfindjobgroup_count migsnrecommendforjob migsnrecommendforjobnamelist migsnrecommendforjobname1 migsnrecommendforjobname2 migsnrecommendforjobname3 migsnrecommendforjobname4 migsnrecommendforjobname5 migsnrecommendforjobname6 migsnrecommendforjobname7 migsnrecommendforjobgroup_count migsnrecojobsuccess migsnrecojobsuccessnamelist migsnrecojobsuccessname1 migsnrecojobsuccessname2 migsnrecojobsuccessname3 migsnrecojobsuccessname4 migsnrecojobsuccessname5 migsnrecojobsuccessname6 migsnrecojobsuccessname7 migsnrecojobsuccessgroup_count mignbercontactphone mignberpersonfamilyevent migcontactlist migcontactlist_1 migcontactlist_2 migcontactlist_3 migcontactlist_4 migcontactlist_5 migcontactlist_6 migcontactlist_7 migcontactlist_8 migcontactlist_9 migcontactgroup_count migdummycontactleaders migcontactleaders mignetworktrustneighborhood mignetworktrustemployees mignetworkpeoplehelping mignetworkhelpkinmember miga1 miga2 miga3 miga4 miga5 miga6 miga7 miga8 miga9 miga10 miga11 miga12 migb1 migb2 migb3 migb4 migb5 migb6 migb7 migb8 migb9 migb10 migb11 migb12 migenjoypeople migcurious migorganized migmanagestress miginterestedbyart migtryhard migworkwithother migmakeplans migsharefeelings mignervous migstickwithgoals migrepetitivetasks migshywithpeople migworkhard migchangemood migunderstandotherfeeling miginventive migenthusiastic migfeeldepressed migappointmentontime migtrustingofother miggoaftergoal migeasilyupset migtalktomanypeople migliketothink migfinishwhatbegin migputoffduties migrudetoother migfinishtasks migtoleratefaults migworryalot migeasilydistracted migkeepworking migcompleteduties migtalkative mignewideas migstaycalm migforgiveother migactiveimagination migexpressingthoughts mighelpfulwithothers migcanreadcard1a migcanreadcard1b migcanreadcard1c migcanreadcard2 mignumeracy1 mignumeracy2 mignumeracy3 mignumeracy4 miglocuscontrol1 miglocuscontrol2 miglocuscontrol3 miglocuscontrol4 miglocuscontrol5 miglocuscontrol6 migab1 migab2 migab3 migab4 migab5 migab6 migab7 migab8 migab9 migab10 migab11 migab12 migmarriagedate {
local new=substr("`x'",4,.)
rename `x' `new'
}

rename parent_key HHID2022
rename key parent_key
order HHID2022 parent_key base
drop if name==""




********** Add contactgroup
preserve
use"NEEMSIS2track-contactgroup", clear
drop if migcontactnumber==.
drop base setofmigcontactgroup key

destring migcontactid, replace
reshape wide migcontactname migcontactnumber, i(parent_key) j(migcontactid)

foreach x in migcontactnumber {
rename `x'1 `x'_headbusi
rename `x'2 `x'_police
rename `x'3 `x'_civilservant
rename `x'4 `x'_bankemployee
rename `x'5 `x'_panchayat
rename `x'6 `x'_council
rename `x'7 `x'_recruiter
rename `x'8 `x'_trade
}

drop migcontactname*
save"NEEMSIS2track-contactgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-contactgroup_v2"
drop if _merge==2
drop _merge



********** Add migrationjobidgroup
preserve
use"NEEMSIS2track-migrationjobidgroup", clear
drop migmigrationarea_1 migmigrationarea_2 migmigrationarea_3 migmigrationarea_4 migmigrationarea_5 migmigrationarea_6 migmigrationarea_label migmigrationtype_label migmigrationdurationfrequency_la migdummybacktovillage_label migmigrationtravelpayment_label migmigrationfindjob_label migmigrationjobtype_label migmigrationjobtype2_label migmigrationwagetype_label migmigrationpension_label migmigrationbonus_label migmigrationinsurance_label migmigrationchild_label migmigrationmainoccup_label migmigrationskill_label migmigrationreason_label migmigrationfindjob_1 migmigrationfindjob_2 migmigrationfindjob_3 migmigrationfindjob_4 migmigrationfindjob_5 migmigrationfindjob_6 migmigrationskill_1 migmigrationskill_2 migmigrationskill_3 migmigrationskill_4 migmigrationskill_5 migmigrationreason_1 migmigrationreason_2 migmigrationreason_3 migmigrationreason_4 migmigrationreason_5 migmigrationreason_6 migmigrationreason_7 migmigrationreason_8 migmigrationreason_9 migmigrationreason_10 migmigrationreason_77 base setofmigmigrationjobidgroup key

destring migmigrationjobid, replace
rename migmigrationjobtype2 migmigrationjobtypetwo
reshape wide migmigrationjobname migmigrationarea migmigrationplace migmigrationdistance migmigrationtype migmigrationdurationfrequency migmigrationdurationinmonth migdummybacktovillage migmigrationtravelcost migmigrationtravelpayment migmigrationtenure migmigrationfindjob migmigrationjobtype migmigrationjobtypetwo migmigrationwagetype migmigrationsalary migmigrationpension migmigrationbonus migmigrationinsurance migmigrationchild migmigrationmainoccup migmigrationskill migmigrationreason migmigrationotherreason, i(parent_key) j(migmigrationjobid)

foreach x in migmigrationarea migmigrationplace migmigrationdistance migmigrationtype migmigrationdurationfrequency migmigrationdurationinmonth migdummybacktovillage migmigrationtravelcost migmigrationtravelpayment migmigrationtenure migmigrationfindjob migmigrationjobtype migmigrationjobtypetwo migmigrationwagetype migmigrationsalary migmigrationpension migmigrationbonus migmigrationinsurance migmigrationchild migmigrationmainoccup migmigrationskill migmigrationreason migmigrationotherreason {
local new=substr("`x'",4,.)
rename `x'1 `new'_brick
rename `x'2 `new'_sugar
rename `x'3 `new'_const
rename `x'4 `new'_nagri
rename `x'5 `new'_agri
rename `x'6 `new'_priv
rename `x'7 `new'_publi
rename `x'8 `new'_self
}

drop migmigrationjobname*
save"NEEMSIS2track-migrationjobidgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-migrationjobidgroup_v2"
drop if _merge==2
drop _merge



********** Add remittancesreceivedsourceidgroup
preserve
use"NEEMSIS2track-remittancesreceivedsourceidgroup", clear
drop v4 v6 migremittancesreceivedsourcehh_l v10 v12 migremittancesreceivedfrequency_ migremittancesreceivedservices_l migremittancesreceivedservices_1 migremittancesreceivedservices_2 migremittancesreceivedservices_3 migremittancesreceivedservices_4 migremittancesreceivedservices_5 migremittancesreceivedservices_7 key setofmigremittancesreceivedsourc

foreach x in recipientsourceid recipientsourcenam receivedsourcedumm receivedsourcerela receivedsourcehh receivedsourceoccu receivedsourceplac receivedfrequency receivedamount receivedtotalamoun receivedservices receivedservicesot {
rename migremittances`x' rem`x'
}

rename v25 remreceivedsourceoccupother

destring remrecipientsourceid, replace
reshape wide remrecipientsourcenam remreceivedsourcedumm remreceivedsourcerela remreceivedsourcehh remreceivedsourceoccu remreceivedsourceplac remreceivedfrequency remreceivedamount remreceivedtotalamoun remreceivedservices remreceivedsourceoccupother remreceivedservicesot, i(parent_key) j(remrecipientsourceid)

save"NEEMSIS2track-remittancesreceivedsourceidgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-remittancesreceivedsourceidgroup_v2"
drop if _merge==2
drop _merge



********** Add remittancessentidgroup
preserve
use"NEEMSIS2track-remittancessentidgroup", clear
drop migremittancessentdummyvillage_l migremittancessentrelation_label migremittancessentoccup_label migremittancessentplace_label migremittancessentfrequency_labe migremittancessentservices_label migremittancessentservices_1 migremittancessentservices_2 migremittancessentservices_3 migremittancessentservices_4 migremittancessentservices_5 migremittancessentservices_77 key setofmigremittancessentidgroup base

foreach x in sentid sentname sentdummyvillage sentrelation sentoccup sentplace sentfrequency sentamount senttotalamount sentservices sentsourceoccupoth sentservicesother {
rename migremittances`x' rem`x'
}

destring remsentid, replace
reshape wide remsentname remsentdummyvillage remsentrelation remsentoccup remsentplace remsentfrequency remsentamount remsenttotalamount remsentservices remsentsourceoccupoth remsentservicesother, i(parent_key) j(remsentid)

save"NEEMSIS2track-remittancessentidgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-remittancessentidgroup_v2"
drop if _merge==2
drop _merge



********** Add wagejobpaymentinkindgroup
preserve
use"NEEMSIS2track-wagejobpaymentinkindgroup", clear
drop if migwagejobpaymentinkindvalue==.
drop key setofmigwagejobpaymentinkindgrou

foreach x in migwagejobpaymentinkindid migwagejobpaymentinkindname migwagejobpaymentinkindvalue {
local new=substr("`x'",4,.)
rename `x' `new'
}

destring wagejobpaymentinkindid, replace
reshape wide wagejobpaymentinkindname wagejobpaymentinkindvalue, i(parent_key) j(wagejobpaymentinkindid)

foreach x in wagejobpaymentinkindvalue {
rename `x'1 `x'_clot
rename `x'2 `x'_food
rename `x'3 `x'_tran
}

drop wagejobpaymentinkindname*

save"NEEMSIS2track-wagejobpaymentinkindgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-wagejobpaymentinkindgroup_v2"
drop if _merge==2
drop _merge



********** Add formalsocialcapital
preserve
use"NEEMSIS2track-formalsocialcapital", clear
drop if migassociationname==""
drop migassohelpjob_1 migassohelpjob_2 migassohelpjob_3 migassohelpjob_4 migassohelpjob_5 migassohelpjob_77 migassohelpbusiness_1 migassohelpbusiness_2 migassohelpbusiness_3 migassohelpbusiness_4 migassohelpbusiness_5 migassohelpbusiness_6 migassohelpbusiness_7 migassohelpbusiness_77 key setofmigformalsocialcapital base *_label

destring migassociationid, replace
reshape wide migassociationtype migassociationname migassodegreeparticip migassosize migdummyassorecommendation migdummyassohelpjob migassohelpjob migassocotherhelpjob migdummyassohelpbusiness migassohelpbusiness migassootherhelpbusiness setofmigsnrecommendassoid, i(parent_key) j(migassociationid)

foreach x in migassociationtype2 migassociationname2 migassodegreeparticip2 migassosize2 migassohelpjob2 migassocotherhelpjob2 migassohelpbusiness2 migassootherhelpbusiness2 migassociationtype5 migassociationname5 migassodegreeparticip5 migassosize5 migassohelpjob5 migassocotherhelpjob5 migassohelpbusiness5 migassootherhelpbusiness5 migassociationtype6 migassociationname6 migassodegreeparticip6 migassosize6 migassohelpjob6 migassocotherhelpjob6 migassohelpbusiness6 migassootherhelpbusiness6 migassociationtype7 migassociationname7 migassodegreeparticip7 migassosize7 migassohelpjob7 migassocotherhelpjob7 migassohelpbusiness7 migassootherhelpbusiness7 migassociationtype9 migassociationname9 migassodegreeparticip9 migassosize9 migassohelpjob9 migassocotherhelpjob9 migassohelpbusiness9 migassootherhelpbusiness9 migdummyassorecommendation9 migdummyassorecommendation7 migdummyassorecommendation6 migdummyassorecommendation5 migdummyassorecommendation2 migdummyassohelpjob9 migdummyassohelpjob7 migdummyassohelpjob6 migdummyassohelpjob5 migdummyassohelpjob2 migdummyassohelpbusiness9 migdummyassohelpbusiness7 migdummyassohelpbusiness6 migdummyassohelpbusiness5 migdummyassohelpbusiness2 {
local new=substr("`x'",4,.)
rename `x' `new'
}


foreach x in associationtype associationname assodegreeparticip assosize dummyassorecommendation dummyassohelpjob assohelpjob assocotherhelpjob dummyassohelpbusiness assohelpbusiness assootherhelpbusiness setofmigsnrecommendassoid {
rename `x'2 `x'_SHG
rename `x'5 `x'_pancha
rename `x'6 `x'_polit
rename `x'7 `x'_pro
rename `x'9 `x'_relig
}

save"NEEMSIS2track-formalsocialcapital_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-formalsocialcapital_v2"
drop if _merge==2
drop _merge




********** Rename all
foreach x in migcontactnumber_bankemployee migcontactnumber_civilservant migcontactnumber_council migcontactnumber_headbusi migcontactnumber_panchayat migcontactnumber_police migcontactnumber_recruiter migcontactnumber_trade {
local new=substr("`x'",4,.)
rename `x' `new'
}

rename parent_key setofmigrants



********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore



save"NEEMSIS2track-migindiv", replace
****************************************
* END













****************************************
* Occupations
****************************************

use"NEEMSIS2track-migoccupations", clear


********** Clear variables
drop migbusinessskill_1 migbusinessskill_2 migbusinessskill_3 migbusinessskill_4 migbusinessskill_77 migbusinesssourceinvest_1 migbusinesssourceinvest_2 migjoblocation_1 migjoblocation_2 migjoblocation_3 migjoblocation_4 migjoblocation_5 migjoblocation_6 migjoblocation_7 migrelationemployer_1 migrelationemployer_2 migrelationemployer_3 migrelationemployer_4 migrelationemployer_5 migrelationemployer_6 migrelationemployer_7 migrelationemployer_8 migrelationemployer_9 migrelationemployer_10 migrelationemployer_11 migrelationemployer_66 migrelationemployer_99 migcasteemployer_1 migcasteemployer_2 migcasteemployer_3 migcasteemployer_4 migcasteemployer_5 migcasteemployer_6 migcasteemployer_7 migcasteemployer_8 migcasteemployer_9 migcasteemployer_10 migcasteemployer_11 migcasteemployer_12 migcasteemployer_13 migcasteemployer_14 migcasteemployer_15 migcasteemployer_16 migcasteemployer_66 migcasteemployer_77 migadvancebalanceproblem_1 migadvancebalanceproblem_2 migadvancebalanceproblem_3 migadvancebalanceproblem_4 migadvancebalanceproblem_5 migadvancebalanceproblem_6 migadvancebalanceproblem_77 migkindofwork_label migkindofwork2_label migbusinesscastebased_label migbusinessskill_label migbusinesslossinvest_label migbusinesssourceinvest_label migdummybusinesslabourers_label migjoblocation_label migtypewageemployer_label migrelationemployer_label migcasteemployer_label migsalariedjobtype_label migsalariedwagetype_label migsalariedjobbonus_label migsalariedjobinsurance_label migsalariedjobpension_label migsalariedcontract_label migdummyadvance_label migmigrationadvanceprovider_labe migmigrationadvancefeel_label migdummyadvancebalance_label migadvancebalanceproblem_label migadvancebalanceperception_labe

foreach x in migoccupationnumber migoccupationname migkindofwork migkindofwork2 migmonthsayear migdaysamonth mighoursaday migannualincome mighoursayear migkeep_occupposition migyearestablishment migbusinesscastebased migbusinessskill migbusinessamountinvest migbusinesslossinvest migbusinessskillother migbusinesslossinvestamount migbusinesssourceinvest migotherbusinesssourceinvestment migbusinesssourceinvestgroup_cou migdummybusinesslabourers mignbbusinesslabourers migbusinesslabourers_count migjoblocation migjobdistance migjoblocationname migtypewageemployer migrelationemployer migcasteemployer migothercasteemployer migsalariedjobtype migsalariedwagetype migsalariedjobbonus migsalariedjobinsurance migsalariedjobpension migsalariedcontract migsalariedjobtenure migsalariedjobkindbonus migsalariedjobbonusamount migdummyadvance migmigrationadvanceamount migmigrationadvanceprovider migmigrationadvancefeel migdummyadvancebalance migadvanceamountbalance migadvancebalanceproblem migadvancebalanceperception migadvancebalanceperceptionopen migadvancebalanceproblemother {
local new=substr("`x'",4,.)
rename `x' `new'
}

order parent_key key
rename parent_key migkey
rename key parent_key



********** Add businesslabourers
preserve
use"NEEMSIS2track-businesslabourers", clear
drop v4 migrelationshipbusinesslabourer_ migcastebusinesslabourer_label migbusinesslabourertypejob_label migbusinesslabourerwagetype_labe migbusinesslabourerbonus_label migbusinesslabourerinsurance_lab migbusinesslabourerpension_label key setofmigbusinesslabourers

foreach x in migbusinesslabourernumber mignamebusinesslabourer migdummybusinesslabourerhhmember migaddressbusinesslabourer migrelationshipbusinesslabourer migcastebusinesslabourer migbusinesslabourertypejob migbusinesslabourerwagetype migbusinesslabourerbonus migbusinesslabourerinsurance migbusinesslabourerpension migbusinesslabourerdate {
local new=substr("`x'",4,.)
rename `x' `new'
}

rename businesslabourernumber businesslabourerid
destring businesslabourerid, replace
reshape wide namebusinesslabourer dummybusinesslabourerhhmember addressbusinesslabourer relationshipbusinesslabourer castebusinesslabourer businesslabourertypejob businesslabourerwagetype businesslabourerbonus businesslabourerinsurance businesslabourerpension businesslabourerdate, i(parent_key) j(businesslabourerid)

save"NEEMSIS2track-businesslabourers_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-businesslabourers_v2"
drop if _merge==2
drop _merge



********** Add businesssourceinvestgroup
preserve
use"NEEMSIS2track-businesssourceinvestgroup", clear
drop if mignumberbusinessloan==.
drop key setofmigbusinesssourceinvestgrou base

destring migbusinessloannumber, replace
rename migbusinessloannumber migbusinessloanid
rename migbusinessloanid businessloanid
rename migbusinessloanname businessloanname
rename mignumberbusinessloan numberbusinessloan
reshape wide businessloanname numberbusinessloan setofmigsnbusilendid, i(parent_key) j(businessloanid)

foreach x in numberbusinessloan setofmigsnbusilendid {
rename `x'1 `x'_loan
rename `x'2 `x'_capital
}

drop businessloanname*

save"NEEMSIS2track-businesssourceinvestgroup_v2", replace
restore

merge 1:1 parent_key using "NEEMSIS2track-businesssourceinvestgroup_v2"
drop if _merge==2
drop _merge



********** Order
drop setofmigbusinesssourceinvestgrou setofmigoccupations setofmigbusinesslabourers base

rename migdatestartoccup datestartoccup
rename migkey setofmigoccupations

split parent_key, p(/)
drop parent_key2 parent_key3
rename parent_key1 HHID2022
order HHID2022


********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore


save"NEEMSIS2track-migoccupations_v2", replace
****************************************
* END













****************************************
* Occupations
****************************************
use"NEEMSIS2track-occupations", clear
drop kindofwork_label kindofwork2_label setofoccupations base key


order parent_key
rename parent_key setofoccupations

split setofoccupations, p(/)
drop setofoccupations2
rename setofoccupations1 HHID2022
order HHID2022

********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore


save"NEEMSIS2track-occupations_v2", replace
****************************************
* END

















****************************************
* Append occupations
****************************************
use"NEEMSIS2track-occupations_v2", clear

append using "NEEMSIS2track-migoccupations_v2"

rename occupationnumber occupationid
destring occupationid, replace

order setofoccupations setofmigoccupations



********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore


save"NEEMSIS2-tracking_occupations_v1", replace
*save"CLEAN\NEEMSIS2-tracking_occupations_v1", replace
****************************************
* END















****************************************
* Append individuals
****************************************
use"NEEMSIS2track-nonmigindiv", clear

append using "NEEMSIS2track-migindiv"

order HHID2022 setofnonmigrants setofmigrants
drop base


********** Dummymigrants
gen dummymigrants=0
replace dummymigrants=1 if setofmigrants!=""
ta setofnonmigrants
ta dummymigrants
order dummymigrants, after(setofmigrants)


********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore



********** Add HH level var
merge m:1 HHID2022 using "NEEMSIS2-tracking_v1.dta"
sort HHID2022 name
order _merge HHID2022 name
sort _merge HHID2022 name

save"NEEMSIS2-tracking_indiv_v1", replace
*save"CLEAN\NEEMSIS2-tracking_indiv_v1", replace
****************************************
* END











****************************************
* SN
****************************************

********** Business lender
use"NEEMSIS2track-snbusilendid.dta", clear
gen snsource="Business lender"
drop *_label
foreach x in migsnbusilendname migsnbusilendrelation migsnbusilendcaste migsnbusilendothercaste migsnbusilendoccup migsnbusilendotheroccup migsnbusilendsex migsnbusilendage migsnbusilendeduc migsnbusilendliving migsnbusilendcompared migsnbusilendduration migsnbusilendmeet migsnbusilendfrequency migsnbusilendothermeet migsnbusilendinvite migsnbusilendreciprocity migsnbusilendintimacy {
local new=substr("`x'",14,.)
rename `x' `new'
}
destring migbusinesslenderid, gen(alterid) 
split parent_key, p(/)
rename parent_key1 HHID2022
drop migbusinesslenderid key setofmigsnbusilendid base
order HHID2022 snsource name
sort HHID2022 name
rename relation relationship
fre occup relationship
foreach x in occup relationship {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}

*INDID
drop parent_key2 parent_key3 parent_key4
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2 parent_key22 parent_key23
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_busilend", replace


********** Find job
use"NEEMSIS2track-snfindjobgroup.dta", clear
gen snsource="Find job"
drop migsnfindjobrelationship_label migsnfindjobrelationship_1 migsnfindjobrelationship_2 migsnfindjobrelationship_3 migsnfindjobrelationship_4 migsnfindjobrelationship_5 migsnfindjobrelationship_6 migsnfindjobrelationship_7 migsnfindjobrelationship_8 migsnfindjobrelationship_9 migsnfindjobrelationship_10 migsnfindjobrelationship_11 migsnfindjobrelationship_12 migsnfindjobrelationship_13 migsnfindjobrelationship_14 migsnfindjobrelationship_15 *_label
foreach x in migsnfindjobnamefromearlier migsnfindjobrelationship migsnfindjobsex migsnfindjobage migsnfindjobcastes migsnfindjobcastesother migsnfindjobeduc migsnfindjoboccup migsnfindjoboccupother migsnfindjobliving migsnfindjobcompared migsnfindjobduration migsnfindjobmeet migsnfindjobmeetother migsnfindjobmeetfrequency migsnfindjobinvite migsnfindjobreciprocity1 migsnfindjobintimacy {
local new=substr("`x'",13,.)
rename `x' `new'
}
rename namefromearlier name
rename castes caste
rename castesother casteother
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof* base
order HHID2022 name
sort HHID2022 name
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
rename meetfrequency frequency

*INDID
drop parent_key2
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_findjob", replace



********** Help mig
use"NEEMSIS2track-snhelpmigid.dta", clear
gen snsource="Help migration"
drop migsnhelpmigrelationship_1 migsnhelpmigrelationship_2 migsnhelpmigrelationship_3 migsnhelpmigrelationship_4 migsnhelpmigrelationship_5 migsnhelpmigrelationship_6 migsnhelpmigrelationship_7 migsnhelpmigrelationship_8 migsnhelpmigrelationship_9 migsnhelpmigrelationship_10 migsnhelpmigrelationship_11 migsnhelpmigrelationship_12 migsnhelpmigrelationship_13 migsnhelpmigrelationship_14 migsnhelpmigrelationship_15 *_label migsnhelpmigfindjobhow_1 migsnhelpmigfindjobhow_2 migsnhelpmigfindjobhow_3 migsnhelpmigfindjobhow_4 migsnhelpmigfindjobhow_77
foreach x in migsnhelpmignamenb migsnhelpmigname migsnhelpmigrelationship migsnhelpmigpsex migsnhelpmigage migsnhelpmigcastes migsnhelpmigcastesother migsnhelpmigeduc migsnhelpmigoccuptype migsnhelpmigoccupname migsnhelpmigliving migsnhelpmigcompared migsnhelpmigduration migsnhelpmigmeet migsnhelpmigmeetother migsnhelpmigmeetfrequency migsnhelpmiginvite migsnhelpmigreciprocity1 migsnhelpmigintimacy migsnhelpmigfindjob migsnhelpmigfindjobhow migsnhelpmigfindjobhowother migsnhelpmigmoney migsnhelpmigrecommendations migsnhelpmigrecommendations_labe migsnhelpmigsn {
local new=substr("`x'",13,.)
rename `x' `new'
}
rename psex sex
drop recommendations_labe
count
destring namenb, gen(alterid)
drop namenb
rename castes caste
rename castesother casteother
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof* base
rename occuptype occup
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
rename meetfrequency frequency

*INDID
drop parent_key2
split parent_key, p("[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2
destring parent_key21, gen(migrationstepid)
drop parent_key21
order HHID2022 migrationstepid

save"NEEMSIS2-alter_helpmigration", replace



********** Recommendation asso
use"NEEMSIS2track-snrecommendassoid.dta", clear
gen snsource="Recommendation asso"
drop migsnrecommendassorelationship_l migsnrecommendassorelationship_1 migsnrecommendassorelationship_2 migsnrecommendassorelationship_3 migsnrecommendassorelationship_4 migsnrecommendassorelationship_5 migsnrecommendassorelationship_6 migsnrecommendassorelationship_7 migsnrecommendassorelationship_8 migsnrecommendassorelationship_9 *_label migsnrecommendassomeetfrequency_ migsnrecommendassoreciprocity1_l v15 v16 v17 v18 v19 v20
foreach x in migsnrecommendassonber migsnrecommendassoname migsnrecommendassogroup_count migsnrecommendassorelationship migsnrecommendassosex migsnrecommendassoage migsnrecommendassocastes migsnrecommendassocastesother migsnrecommendassoeduc migsnrecommendassooccup migsnrecommendassooccupother migsnrecommendassoliving migsnrecommendassocompared migsnrecommendassoduration migsnrecommendassomeet migsnrecommendassomeetother migsnrecommendassomeetfrequency migsnrecommendassoinvite migsnrecommendassoreciprocity1 migsnrecommendassointimacy {
local new=substr("`x'",19,.)
rename `x' `new'
}
drop nber group_count
rename castes caste
rename castesother casteother
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof*
rename meetfrequency frequency

*INDID
drop parent_key2 parent_key3
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2 parent_key22
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_recoasso", replace



********** Recommendation for job
use"NEEMSIS2track-snrecommendforjobgroup.dta", clear
gen snsource="Recommendation job"
drop v3 v4 v5 v6 v7 v8 v9 v10 v11 v12 v13 v14 v15 v16 v17 v18 *_label migsnrecommendforjobcompared_lab migsnrecommendforjobfrequency_la v44 migsnrecommendforjobintimacy_lab
foreach x in migsnrecommendforjobnamefromearl migsnrecommendforjobrelationship migsnrecommendforjobsex migsnrecommendforjobage migsnrecommendforjobcastes migsnrecommendforjobcastesother migsnrecommendforjobeduc migsnrecommendforjoboccup migsnrecommendforjoboccupother migsnrecommendforjobliving migsnrecommendforjobcompared migsnrecommendforjobduration migsnrecommendforjobmeet migsnrecommendforjobmeetother migsnrecommendforjobfrequency migsnrecommendforjobinvite migsnrecommendforjobreciprocity1 migsnrecommendforjobintimacy {
local new=substr("`x'",21,.)
rename `x' `new'
}
rename namefromearl name
rename castes caste
rename castesother casteother
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof*

*INDID
drop parent_key2
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_recojob", replace



********** Recruit worker
use"NEEMSIS2track-snrecruitworkergroup.dta", clear
gen snsource="Recruit worker"
drop migsnrecruitworkerrelationship_l migsnrecruitworkerrelationship_1 migsnrecruitworkerrelationship_2 migsnrecruitworkerrelationship_3 migsnrecruitworkerrelationship_4 migsnrecruitworkerrelationship_5 migsnrecruitworkerrelationship_6 migsnrecruitworkerrelationship_7 migsnrecruitworkerrelationship_8 migsnrecruitworkerrelationship_9 v13 v14 v15 v16 v17 v18 *_label migsnrecruitworkermeetfrequency_ migsnrecruitworkerreciprocity1_l
foreach x in migsnrecruitworkernamefromearlie migsnrecruitworkerrelationship migsnrecruitworkersex migsnrecruitworkerage migsnrecruitworkercastes migsnrecruitworkercastesother migsnrecruitworkereduc migsnrecruitworkeroccup migsnrecruitworkeroccupother migsnrecruitworkerliving migsnrecruitworkercompared migsnrecruitworkerduration migsnrecruitworkermeet migsnrecruitworkermeetother migsnrecruitworkermeetfrequency migsnrecruitworkerinvite migsnrecruitworkerreciprocity1 migsnrecruitworkerintimacy {
local new=substr("`x'",19,.)
rename `x' `new'
}
rename namefromearlie name
rename castes caste
rename castesother casteother
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof*
rename meetfrequency frequency

*INDID
drop parent_key2
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_recruitworker", replace



********** Technical help
use"NEEMSIS2track-sntechnicalhelpgroup.dta", clear
gen snsource="Technical help"
drop migsntechnicalhelprelationship_l migsntechnicalhelprelationship_1 migsntechnicalhelprelationship_2 migsntechnicalhelprelationship_3 migsntechnicalhelprelationship_4 migsntechnicalhelprelationship_5 migsntechnicalhelprelationship_6 migsntechnicalhelprelationship_7 migsntechnicalhelprelationship_8 migsntechnicalhelprelationship_9 v13 v14 v15 v16 v17 v18 *_label migsntechnicalhelpmeetfrequency_ migsntechnicalhelpreciprocity1_l
foreach x in migsntechnicalhelpnamefromearlie migsntechnicalhelprelationship migsntechnicalhelpsex migsntechnicalhelpage migsntechnicalhelpcastes migsntechnicalhelpcastesother migsntechnicalhelpeduc migsntechnicalhelpoccup migsntechnicalhelpoccupother migsntechnicalhelpliving migsntechnicalhelpcompared migsntechnicalhelpduration migsntechnicalhelpmeet migsntechnicalhelpmeetother migsntechnicalhelpmeetfrequency migsntechnicalhelpinvite migsntechnicalhelpreciprocity1 migsntechnicalhelpintimacy {
local new=substr("`x'",19,.)
rename `x' `new'
}
rename namefromearlie name
rename castes caste
rename castesother casteother
foreach x in occup {
decode `x', gen(`x'_str)
drop `x'
rename `x'_str `x'
}
split parent_key, p(/)
rename parent_key1 HHID2022
drop key setof*
rename meetfrequency frequency

*INDID
drop parent_key2
split parent_key, p("migquestionnaireid[")
drop parent_key parent_key1
split parent_key2, p("]")
drop parent_key2
destring parent_key21, gen(INDID_mig)
drop parent_key21
order HHID2022 INDID_mig

save"NEEMSIS2-alter_technicalhelp", replace
****************************************
* END








****************************************
* Append SN
****************************************

********** Business lender
use"NEEMSIS2-alter_busilend", clear
append using "NEEMSIS2-alter_findjob"
append using "NEEMSIS2-alter_helpmigration"
append using "NEEMSIS2-alter_recoasso"
append using "NEEMSIS2-alter_recojob"
append using "NEEMSIS2-alter_recruitworker"
append using "NEEMSIS2-alter_technicalhelp"
count
drop base

order HHID2022 snsource name
sort snsource name

ta relationship snsource

replace relationship="Maistry" if relationship=="1"
replace relationship="Own child not living in the house" if relationship=="2"
replace relationship="Sibling not living in the house" if relationship=="3"
replace relationship="Parent not living in the house" if relationship=="4"
replace relationship="Niece/Nephew not living in the house" if relationship=="5"
replace relationship="Other family member not living in the house" if relationship=="6"
replace relationship="Neighbor" if relationship=="7"
replace relationship="Friend" if relationship=="8"
replace relationship="Customer/supplier/colleague" if relationship=="9"
replace relationship="Moneylender" if relationship=="10"
replace relationship="SHG member" if relationship=="11"
replace relationship="Employer" if relationship=="12"
replace relationship="Well known people" if relationship=="13"
replace relationship="Own child living in the house" if relationship=="14"
replace relationship="Spouse" if relationship=="15"

replace relationship="Sibling not living in the house" if relationship=="3 4"

replace relationship="Friends" if relationship=="Friend"

fre relationship

replace alterid=1 if alterid==.


********** Duplicates drop
merge m:1 HHID2022 using "N2track"
drop if _merge==1
drop if _merge==2
drop tokeep _merge
*
preserve
duplicates drop HHID2022, force
count
restore

save"NEEMSIS2-tracking_alter_v1", replace
****************************************
* END
